### ISSUE TITLE
Verify Erlang Client Search

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#105]
Verify that the Erlang Riak Client is able to run search requests against Yokozuna like it does Riak Search.  This is vital for users that are upgrading from RS.

This PR lives here: basho/riak-erlang-client#112

**Comment by coderoshi** [comment]
This is built into testing #38, though ditto on testing the other drivers.

**Comment by coderoshi** [comment]
basho/riak-erlang-client#112 is merged
