### ISSUE TITLE
Verify Java Client Search

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#106]
Verify that the Riak Java Client is able to run search requests against Yokozuna like it does Riak Search.  This is vital for users that are upgrading from RS.
- Verify both HTTP and PB.

**Comment by hazen** [comment]
Java does not use regular PB/HTTP search APIs, instead using an older Map/Reduce interface: https://github.com/basho/riak-java-client#searchmapreduce

Investigating possibility of calling Yokozuna from Map/Reduce

**Comment by rzezeski** [comment]
@javajolt If you don't mind I'm going to take a whack at this issue.

**Comment by hazen** [comment]
I rather assumed this would be the end result of your efforts in Issue #126, anyway

**Comment by rzezeski** [comment]
Before this issue can be resolved need to complete issue #19.

**Comment by rzezeski** [comment]
According to Roach things are working.
