### ISSUE TITLE
Verify Ruby Client Search

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#107]
Verify that the Ruby Riak Client is able to run search requests against Yokozuna like it does Riak Search.  This is vital for users that are upgrading from RS.
- Verify PB.

This PR lives here: basho/riak-ruby-client#113

**Comment by coderoshi** [comment]
Kicked off test and necessary patches https://github.com/basho/riak-ruby-client/tree/er-yokozuna-test

**Comment by coderoshi** [comment]
merged into basho/riak-ruby-client#119
