### ISSUE TITLE
JVM Self Destruct

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#124]
There are many reasons why a JVM may continue running after it's parent erlang process has died, from core dumps to running older Erlang prior to R15B02.

The solr JVM should run a thread which occasionally checks if its PPID=1. If so, the erlang parent process is crashed, and the JVM process should `System.exit()` itself.

Note that there are two parts to this task:
1. get the solr web service to launch a low priority background thread that runs every few seconds.
2. having that thread check for a ppid (which will require some external ps call, or better yet, just writing a script which checks).

Note that the JVM does not have any built-in method for getting a PPID, and many of the "get the PID this way" hacks found out on the interwebs are unreliable (eg. ManagementFactory.getRuntimeMXBean().getName() is not guaranteed).

**Comment by dmitrizagidulin** [comment]
Quick question - does that mean that the Solr instance that YZ spins up should exit once the erlang parent crashes?

**Comment by coderoshi** [comment]
@dmitrizagidulin absolutely yes

**Comment by dmitrizagidulin** [comment]
Ok, cool. Yeah, I've been having to constantly kill -9 the Solr instance, manually.

**Comment by hazen** [comment]
Saving @coderoshi a step by adding his comments:
"there's two parts to this: getting the solr web service to launch a low priority background thread that checks every few seconds, and then having that thread check for a ppid (which will require some external ps call, or better yet, just writing a script which checks). the jvm does not have any built-in method for getting a ppid, and many of the "get the pid this way" hacks are unreliable (eg. ManagementFactory.getRuntimeMXBean().getName() is not guaranteed)"

**Comment by coderoshi** [comment]
@dmitrizagidulin if you've been having to kill -9 the java procs every time, you're probably running R15B01. Only R15B02 is capable of stopping the process when you kill erlang.

**Comment by dmitrizagidulin** [comment]
@coderoshi ahh, I think that's it, yes. Thanks.

**Comment by coderoshi** [comment]
Here's one way to call any custom class through jetty: http://wiki.eclipse.org/Jetty/Reference/jetty.xml_syntax. Example:

```
<Call name="takePill">
  <Arg>
    <New class="com.basho.riak.yokozuna.Cyanide">
    </New>
  </Arg>
</Call>
```

That'll create that object. you can optionally add a new function that it calls, or just spawn the thread via the constructor
