### ISSUE TITLE
Add tests to giddyup

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#132]
Part of integrating into master will include adding the Yokozuna riak tests to giddyup.

**Comment by hazen** [comment]
Issue created: https://github.com/basho/giddyup/issues/86

**Comment by rzezeski** [comment]
The tests have been added to giddyup but the following config needs to be added to the `riak` and `riak_ee` configs in the builders for the tests to be discovered and run.

``` erlang
  {yz_dir, "<path-to-yokozuna>"},
  {test_paths, ["<path-to-yokozuna>/riak_test/ebin"]},
```

Let me know if that works @jaredmorrow.

**Comment by rzezeski** [comment]
@jaredmorrow and I witnessed a successful run of the Yokozuna tests on one of the builders today.  Closing this ticket.

**Comment by hazen** [comment]
Yeah!
