### ISSUE TITLE
Ability To Set Search MapReduce MFA

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#142]
Currently KV is hardcoded to use Riak Search for map-reduce.  As part of migration need to be able to flip switch that tells KV to change from using Riak Search to Yokozuna.  See the comment below for more details.

https://github.com/basho/yokozuna/issues/19#issuecomment-19928053

**Comment by rzezeski** [comment]
This is important for Riak Search migration, see #20.

**Comment by beerriot** [comment]
I submit basho/riak_kv#656 as the fix for this issue.

**Comment by beerriot** [comment]
Scratch that, I submit basho/riak_kv#664 as the fix for this issue.
