### ISSUE TITLE
Remove the Default Index

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#143]
Yokozuna currently indexes all data in all buckets even if not marked for indexing.  This is done so that AAE will work.  Find another way to keep AAE from doing superfluous repairs without requiring the default index.  Some ideas:
- Log file of non-indexed bucket hashes.
- Do both KV and Solr fold when building Yokozuna trees.

**Comment by beerriot** [comment]
Closing this, because default index is gone. We took the second idea option.
