### ISSUE TITLE
Add Visibility and Stats

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#146]
Add visibility and stats.  Visibility could be something like a function to check for common problems and report back status.  I.e. like `riak-admin diag`.  Perhaps integrate Solr stats into the Riak stats, or also track Yokozuna specific stats as well.
- Slow query log?

**Comment by coderoshi** [comment]
@rzezeski wdyt about this? Is this covered by #318?

**Comment by rzezeski** [comment]
No, this is something I'm still working on.

**Comment by rzezeski** [comment]
I marked this as 2.0-beta because I promised the CSEs months ago that there would be a diagnostic tool that would look for obvious issues. You can see my partial work here:

https://github.com/basho/yokozuna/compare/develop...feature;rz;diag

Should this be a blocker for beta? Should it even be in 2.0 at all?

/cc @jonmeredith @gburd @michellep @coderoshi

**Comment by jonmeredith** [comment]
I would mark as 2.0-rc - ready before we can cut a real release candidate
as we need something in there for early adopters to have a chance.

On Mon, Mar 24, 2014 at 11:46 AM, Ryan Zezeski notifications@github.comwrote:

> I marked this as 2.0-beta because I promised the CSEs months ago that
> there would be a diagnostic tool that would look for obvious issues. You
> can see my partial work here:
> 
> develop...feature;rz;diaghttps://github.com/basho/yokozuna/compare/develop...feature;rz;diag
> 
> Should this be a blocker for beta? Should it even be in 2.0 at all?
> 
> /cc @jonmeredith https://github.com/jonmeredith @gburdhttps://github.com/gburd
> @michellep https://github.com/michellep @coderoshihttps://github.com/coderoshi
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/basho/yokozuna/issues/146#issuecomment-38476746
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by rzezeski** [comment]
Initial version of the diagnostic module is in (`yz_diag`). Finally closing this little guy.
