### ISSUE TITLE
Yokozuna and Bucket Types

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#176]
https://github.com/basho/riak/issues/362

Add bucket type support to Yokozuna.

Yokozuna will:
- Continue to base index association on bucket properties.
- If the bucket is under the default type then the bucket prop `yz_index` must be set.  This is also the scenario for users migrating from Riak Search.
- If the bucket has a type with `yz_index` set then that bucket will inherit that index association.
- If the bucket has a type with `yz_index` set but also has `yz_index` set as a bucket prop then the latter wins.  This means buckets under one type can point to different indexes.
- Multiple buckets can point to one index.
- A bucket can only have one associated index.
- When migrating Riak Search indexes keep them under default type as to avoid moving the KV data.
- Add logic to `yz_index:associated_buckets(Index)` to understand types.  I.e. if a type has `yz_index` set and has 3 buckets underneath it then those 3 buckets, along with any other buckets pointing to `Index`, should be returned.
- Add special field `_yz_bt` to designate the bucket type of the Solr document.

**Comment by rzezeski** [comment]
After talking with @jrwest tonight it sounds like `get_bucket` will handle the property inheritance automatically.  I.e. Yokozuna doesn't have to care where the index name comes from.  It's up to the user to know that a type property applies to all its buckets but can be overridden by a bucket property.

It sounds like `yz_index:associated_buckets` could be a problem.  Perhaps the best thing to do there is just return any types with `yz_index` set along with and bucket overrides.  E.g.

``` erlang
-spec assocaited(Index) -> [{type, [type_name()]}, {buckets, [bucket_name()]}].
```

**Comment by jrwest** [comment]
one thing I forgot to mention when talking about this earlier is `get_bucket` can now return `{error, no_type}` when passed `{BucketType, BucketName}` and `BucketType` d.n.e (or is inactive)

**Comment by rzezeski** [comment]
This will rely on basho/riak_kv#711.
