### ISSUE TITLE
Waiting for riak_kv causes riak to hang on start

### ISSUE THREAD

**Issue by jrwest** [basho/yokozuna#177]
Even when yoko is disabled it causes riak to hang at the console on start (the console takes no input) during the time the kv service is starting. Removing [this line](https://github.com/basho/yokozuna/blob/develop/src/yz_app.erl#L37) gets rid of the hang. Based on discussion, its not immediately apparent if the `wait_for_service` call is  still needed. If it is, it would be nice to call it only when yoko is enabled (inside the case) or find a similar method that doesn't block the console.

**Comment by rzezeski** [comment]
Tentatively marking this for 1.1.0.  Would like to remove if possible but need to a) run Yokozuna riak tests and b) deal with any code paths that expect riak_kv to be up like schema administration (could change the code to deal with service unavailable).
