### ISSUE TITLE
100% CPU on VM Crash

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#18]
If the Erlang VM crashes then the [shell wrapper](https://github.com/rzezeski/yokozuna/blob/0.1.0/priv/sig-wrapper) for Solr
will consume 100% CPU until the Java process is killed.  I'm hoping
this is just an oversight in the script like handling a signal.  I
don't particularly like that Yokozuna uses this wrapper but when I
wrote this piece months ago I couldn't find a way for Erlang ports to
send signals to processes.  I'm open to alternative approaches.

**Comment by coderoshi** [comment]
This is a great opportunity to replace this script with a more robust monitoring system. I'm thinking using a JMX monitor, and sending a graceful shutdown signal through JMX. Adding a timeout to just SIGTERM would be a good backup, but most shutdowns would be cleaner.

http://tapestryjava.blogspot.com/2010/11/starting-and-stopping-jetty-gracefully.html

**Comment by coderoshi** [comment]
Your script signal fix seems to have repaired this. Added JMX #24 just for an added bonus.

Startup as normal, run `jconsole`, and attach to the jetty/solr service. Fun ensues.

**Comment by coderoshi** [comment]
I rescind my statement. This is still a problem, marksteele ran across this issue after adding 4 million docs to one index.

**Comment by rzezeski** [comment]
Fixed by #28
