### ISSUE TITLE
Explain behavior/format of "bucket" and "index" mapred inputs

### ISSUE THREAD

**Issue by beerriot** [basho/yokozuna#181]
We need to add two bits of information to MapReduce documentation, as a result of #174:
1. specifying a "bucket" always searches the whole index related to that bucket, and users should add their own filter on the `_yz_rb` field if they have associated more than one bucket with an index, and only want specific buckets in their results
2. users can use "index" to name an index instead of a bucket, i.e. `{"index":Index,"query":Query,"filter":Filter}` instead of `{"bucket":Bucket,"query"...}`

**Comment by rzezeski** [comment]
Bryan and I changed stances one last time.  Forget all the fancy gimmicks.  The "bucket" IS the index name.  Very simple.  We will want to document that if previous Riak Search users or some unsuspecting user passes the following as input to a map-reduce job that the "bucket" value will be used as the index name in Yokozuna.

```
"inputs":{"bucket":"foo", "query":"bar"}
```

The above will use the **INDEX** foo to search for the term bar.

**Comment by coderoshi** [comment]
This was all dealt with in the docs basho/basho_docs#853
