### ISSUE TITLE
Make sure Yokozuna works with new object format

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#191]
I'm not sure if Yokozuna currently works if the new object format is used.  Make sure to test that.

**Comment by coderoshi** [comment]
I'm unsure what we would be testing here. The new version format is only concerned with serialization of the RiakObject to_binary and from_binary. `yz_kv:index` accepts a RiakObject, and extracts values, etc., but never touches the binary version. Any test we write would only be testing that the riak_object functions work correctly, not yokozuna.

**Comment by rzezeski** [comment]
Okay, I just wanted to make sure we didn't overlook anything. I didn't necessarily expect a test. If it doesn't affect the Yokozuna index path then it sounds like we are good to go. :+1:
