### ISSUE TITLE
Riak Search Migration [JIRA: RIAK-1713]

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#20]
Provide methods and documentation for migrating from Riak Search.
## Checklist
- [x] Add function to flip query service from RS to Yokozuna (basho/riak_api#31)
- [x] Add riak-admin cmd to flip query service?
- [x] Add YZ AAE status reporting (#154)
- [x] Add YZ AAE status to `raik-admin aae-status`
- [ ] Add command for immediate re-index
- [x] Test that AAE migration works
- [ ] Test that command migration works (i.e. some command to immediately re-index under Yokozuna)
- [x] Document migration steps
- [x] Document migration of schema
- [ ] Create example Solr schema that represents approximation of default RS schema
## Migration by AAE

A nice benefit of active-anti-entropy (AAE) is that it provides a
"free" upgrade path from Riak Search to Yokozuna.  After upgrading a
node queries would still go to Riak Search but new data would
temporarily be indexed by both Riak Search and Yokozuna.  Over time
AAE would repair the missing data from Yokozuna, completing it's
index.  After AAE has repaired everything the Riak Search hook could
be removed and queries could be redirected to Yokozuna.  This simple
description hand-waves over a few things.
- How to determine when AAE has repaired all the data?
- What does it mean to "redirect the query"?  Would it require the
  client switching the HTTP resource it points to?  Would it be a
  dynamic re-binding in Riak so that the Riak Search Solr interface
  now points to Yokozuna?
- Riak Search tries it's best to look and act like Solr but at the end
  of the day it isn't Solr.  The results, in terms of ranking and
  format, will probably change.  How will this affect clients?  Will
  the Riak Search client work against Yokozuna?  Should there be a
  translation?  Should we just force the client to use a real Solr
  client?  If so, how do you properly integrate existing Solr clients
  with Riak clients?  E.g. a client runs a Solr query for the keys but
  then runs a Riak query for the object data.  Are there easy ways to make
  this one operation?

**Comment by rzezeski** [comment]
## Migration By Fold
- Migration by AAE has overhead of Riak Read per object. (Should we be using read-repair for AAE?)
- We could use vnode fold directly for more efficient migration.
1. get list of indexed buckets
2. fold over objects in each bucket
3. send function to fold which re-indexes those objects
- Would need some function or command to invoke this migration method.

**Comment by rzezeski** [comment]
Other things to think about:
- What about schema migration?  If user has custom schema in RS need to document how to create an approximation of that in Solr.  E.g. if using the noop analyzer in RS then use a `string` field type in Solr, etc.
- What about providing a schema that is a translation of the default RS schema.

**Comment by rzezeski** [comment]
I set this to the 2.0-beta tag because there are 3 things that should probably be in 2.0.0 for Riak Search migration.
1. Add a command to flip the search service from riak_search to yokozuna.
2. Add yokozuna AAE status to `riak-admin aae-status` (or maybe there should be `riak-admin search aae-status`). Users would use this to determine when AAE has done a full round of repair.
3. Add a command to immediately re-index a bucket. This would allow users to avoid waiting for AAE to repair everything.

I think 1 & 2 are pretty easy but not sure about 3. I think we could leave 3 for 2.0.1/2.1.0 if people ask for it and require migration to occur via AAE only for 2.0.0.

This completely ignores the documentation that has to be done around migration which should probably be a 2.0 blocker as well.

Thoughts?

/cc @jonmeredith @michellep @gburd @coderoshi

**Comment by coderoshi** [comment]
Migration docs are under construction
https://github.com/basho/basho_docs/blob/2.0.0/source/languages/en/riak/ops/advanced/upgrading-search-2.md

**Comment by rzezeski** [comment]
The re-index command will not make it for 2.0.0 but the documentation still needs to be done.

**Comment by coderoshi** [comment]
@rzezeski basho/basho_docs#1087

**Comment by coderoshi** [comment]
@rzezeski what more of this issue needs to be done for 2.0? Can we mark the rest for the next milestone?

**Comment by coderoshi** [comment]
fat finger closed. reopened.

**Comment by rzezeski** [comment]
Yea, I need to give the documentation a look just to make sure we covered all the steps and then the rest of the tasks (re-index command) can be moved to 2.0.1.

**Comment by michellep-basho** [comment]
Ryan you can move any pending docs to 2.0.1, which is currently being used a placeholder for the 2.0 release (versus the RC).

**Comment by rzezeski** [comment]
@michellep There is a 2.0 tag on all  the repos.  I'll use that.

**Comment by rzezeski** [comment]
I made my updates to the migration documentation here: https://github.com/basho/basho_docs/pull/1150

Moving this to 2.0.1 since the reindex command still needs to be implemented.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by Basho-JIRA** [comment]
[~seancribbs], can this be closed? 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by zeeshanlakhani** [comment]
@seancribbs, I'd say so.

**Comment by Basho-JIRA** [comment]
Seems already fixed, this is just lingering. 

**_[posted via JIRA by Sean Cribbs]**_
