### ISSUE TITLE
Create a Migration Path from Search to Yoko

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#25]
@kenperkins mentioned wanting a mechanism to move from Search to YZ in the future. It would be a nice thing to provide.

**Comment by kenperkins** [comment]
We @clipboard have Riak Search as ~95% of our core app scenarios. So being able to migrate from RS to Yokozuna without having to reindex everything is to a degree a must have for us.

As an example, we've been reindexing this week do to merge_index corruption and it's already been running for over 6 days, and we're barely 60% done.

**Comment by rzezeski** [comment]
I'm closing this issue as it's covered in #20.

The migration paths will probably all require re-indexing but not as expensive as reading/re-writing everything in a tight loop.  In fact, even with Riak Search, a better way to re-index everything is to use map-reduce to re-invoke the hook on all objects as described in this riak-users post.

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-October/009861.html
