### ISSUE TITLE
Two bugs in `yz_kv:should_handoff`

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#258]
@jrwest brought 2 issues to my attention related to `yz_kv:should_handoff`.
1. If Yokozuna is disable then this function should return `true`. Otherwise KV handoff could be blocked.
2. If Yokozuna is enabled a capability check must be made with remote node before doing remote call to get hash. See https://github.com/basho/yokozuna/blob/develop/src/yz_kv.erl#L165

The second issue can be solved by checking for the Yokozuna service on the remote side. If the service is not on remote then return `true` to allow handoff to complete. I don't think capabilities are needed.

**Comment by jrwest** [comment]
capabilities would allow you to perform a local-only call but since you are already making one remote call... {shrug}

EDIT: reworded, sorry tired.

**Comment by rzezeski** [comment]
@jrwest Does capabilities take into account if service is disabled? There could be case where user doesn't enable Yokozuna on all nodes (which would be a mistake, sigh non-global config). In that case the service would be down and `should_handoff` could return true so as not to block KV handoff. I don't think capabilities can deal with this situation, can it?

**Comment by jrwest** [comment]
@rzezeski if I understand you correctly, what I've usually done in this situation is based on the app.config change how the capability is registered when the application starts. This way the cluster can't converge to "is enabled" when a single node is still disabled. 

https://github.com/basho/riak_kv/blob/develop/src/riak_kv_app.erl#L170-L172
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_app.erl#L322-L327

**Comment by rzezeski** [comment]
I found that condition 1 is not an issue. KV handoff will proceed just fine with the existing check. I verified this via the `verify_handoff` test. However, I'm still going to change the `should_handoff` function to only make calls if Yokozuna is enabled to avoid any breakage in the future.

**Comment by rzezeski** [comment]
My fix for the second condition will be to check for the Yokozuna service on the other side. I tried to use capabilities but it currently has a race condition which causes the 2.0 node to think the 1.4.2 node has Yokozuna (which is impossible) and cause a crash on the call to the metadata server.

If the service is down (meaning Yokozuna is disabled, Solr is down, or pre 2.0 node) then bypass the metadata check. Otherwise perform it. Simple. A modified version of `verify_handoff_mixed` failed before the modification with the expected rpc failures and it passes after the modification. PR incoming once I get another PR in.

**Comment by jonmeredith** [comment]
Would be very interesting to understand the 1.4.2/2.0 capabilities race.
 That seems... bad.

On Tue, Jan 14, 2014 at 4:11 PM, Ryan Zezeski notifications@github.comwrote:

> My fix for the second condition will be to check for the Yokozuna service
> on the other side. I tried to use capabilities but it currently has a race
> condition which causes the 2.0 node to think the 1.4.2 node has Yokozuna
> (which is impossible) and cause a crash on the call to the metadata server.
> 
> If the service is down (meaning Yokozuna is disabled, Solr is down, or pre
> 2.0 node) then bypass the metadata check. Otherwise perform it. Simple. A
> modified version of verify_handoff_mixed failed before the modification
> with the expected rpc failures and it passes after the modification. PR
> incoming once I get another PR in.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/yokozuna/issues/258#issuecomment-32318218
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by rzezeski** [comment]
@jonmeredith According to @jrwest this is a known issue with a fix coming?

**Comment by jrwest** [comment]
I don't think we have an issue for this one filed. I couldn't find it quickly but maybe @jtuple or @cmeiklejohn know? I will try to reproduce locally/make a riak_test and get an issue open if I don't hear otherwise.
