### ISSUE TITLE
Add deprecation notices to Riak Search docs and startup

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#272]
Add very obvious, very large deprecation warnings to Riak Search documentation and log a deprecation warning on Riak Search startup.

/cc @coderoshi

**Comment by coderoshi** [comment]
This is already a thing basho/basho_docs#741

**Comment by rzezeski** [comment]
N=2, PROBLEM?

**Comment by rzezeski** [comment]
Can we get a gif of someone shooting themselves in the foot with a gun for the deprecation banners?

**Comment by rzezeski** [comment]
https://www.youtube.com/watch?v=mhIJOVD8hwY&oref=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DmhIJOVD8hwY&has_verified=1

**Comment by coderoshi** [comment]
![](http://www.ncbusinesslitigationreport.com/uploads/image/shoot%20in%20foot.jpg)

**Comment by coderoshi** [comment]
:shoe::gun:

**Comment by rzezeski** [comment]
![shark-raptor-gun-dynamite](https://f.cloud.github.com/assets/208153/1864534/3d6c80fa-77f6-11e3-81fa-035b4cbf3f5d.png)
