### ISSUE TITLE
Add Yokozuna to `riak-admin aae-status`

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#292]
Yokozuna AAE should be reported along with KV. A `Failed` column should be added to the `Keys Repaired` section too.

See #248.

**Comment by rzezeski** [comment]
I'm marking this as 2.0-RC but not really sure.

/cc @jonmeredith @gburd @michellep @coderoshi

**Comment by jonmeredith** [comment]
2.0-RC works for me.  Need to be able to inspect this stuff in the wild.
