### ISSUE TITLE
Add KV hook to halt incongruous bucket/index n_vals

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#297]
We scrumbled today about about the new index n_val settings. Jon expressed concern about the lack of any real constraints on keeping bucket and index n_vals in sync. I re-proposed the bucket props hook option, whereby, when a user sets bucket or type properties, the hook will check that an associated seach_index has the same n_val. If the bucket does not have the same n_val as the bucket, then the update will fail. This has some upsides and downsides:

upsides:
- makes it harder for users to shoot themselves in the foot with different n_vals
- puts a mechanism in place for other potential checks (an associate_index security setting? optionally turning off 1:M or non-typed bucket support?)

downsides:
- changing n_val requires users detach a bucket from an index, altering n_val on both index and bucket, then reattach
- yet another point where KV is tied to yokozuna

I think it's better to include this constraint in now, and potentially remove it later, than to open up users to weird behaviors and rely on CSEs and docs to solve their problems.

**Comment by coderoshi** [comment]
> Wouldn't users be able to change the n_val on the index after associating
> the bucket with it? Or will there be validation added on the index update
> side as well?

@jrwest Validation would happen on update to both bucket on index, but updating index n_val via yokozuna wouldn't matter at all to KV, so I didn't list it as a downside of tighter coupling. We'd simply disallow updating an index n_val as long as any buckets are associated with it, and vice versa.

> It may be too late in the cycle but I mentioned to @rzezeski that it
> should be quick to extend the bucket validator registration to not require
> the application to be a proper riak_core app ("global" validators for lack
> of a better term).  This would at least allow the bucket validation code to
> live in yoko-land.

The validation itself would live in yokozuna in any case. But the call to that validation would be made via KV when bucket props are updated. If you have an idea for registering a yz property validator, that'd be awesome, assuming it's not too late.

**Comment by rzezeski** [comment]
I don't think this needs to be done for 2.0. The RC is 4 days
away. The effects of the N value differing are not catastrophic and
can easily be fixed by changing `n_val` on the index. The new coverage
plan will be calculated after a maximum of 2 seconds. I also plan to
add a check for this in the `yz_diag` module I am working on.

That said, if you feel strongly that this needs to be done now then I
won't stop you. When you say "bucket props hook" I assume you mean
bucket validators? IIRC the validators don't include non-typed buckets
but I think that is fine.

**Comment by jonmeredith** [comment]
Aren't the effects of the N-val differing not finding things you would expect to? (something about indexing yz data on vnodes, coverage plans expecting to be across all vnodes).

I'm concerned it'll be a support issue and source of rabbit holes.

Jon

**Comment by rzezeski** [comment]
> Aren't the effects of the N-val differing not finding things you would expect to?

If the N for the index is < then N for the KV bucket then it will
be less available then it could. If N for the index is higher then
it will have non-deterministic results depending on the partitions
chosen from the ring. So yes, in the second case findings would not
always be as expected.

> I'm concerned it'll be a support issue and source of rabbit holes.

The `yz_diag` tool will be the first thing run for a Yokozuna
ticket. It will look for this. The correction is to change the `n_val`
on the index and wait 2 seconds. I don't see this as a blackhole of
support issues.

That said, we currently don't have support for just changing the
`n_val` for an index. That's an easy change to make for HTTP, not
exactly sure about PB. I guess if we add bucket validtors for `n_val`
then we could make the argument you can't change them and missing that
part of the API would be fine.

**Comment by rzezeski** [comment]
After thinking about this some more I was wrong. It would be
embarrassing and annoying for a user to index a bunch of data only to
realize the N values don't match up.  This change would prevent that
from happening. I'll mark this for Yokozuna 1.0.0 (Riak 2.0).

**Comment by rzezeski** [comment]
This was addressed by #303.
