### ISSUE TITLE
The update handler should probably be renamed

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#312]
The Solr update handler (`solr/core/update`) is well known to any Solr user. Old Riak Search supported indexing via this same interface. It would allow a user to create index entries without a KV object. Yokozuna has no such interface as I'm not sure what the semantics would be. E.g. would it simply index things in solr or would it generate KV objects too?

The problem is that the local Solr nodes that Yokozuna starts do have the update handler in place and they are listening on the canonical URL. This might confuse users, thinking that they can send writes to this URL and it will distributed the data and work with Yokozuna when it will in fact not do any such thing.

It might be wise to rename it to `solr/core/yz_update` or similar. That wouldn't stop users from making this mistake but it would make it a little harder to shoot yourself in the foot.

**Comment by rzezeski** [comment]
I'm moving this to 2.0-RC because there was already an issue where a user confused Solr's port for Riak/Yokozuna's port because the interfaces are the same.  Once we go live with 2.0.0 it may be close to impossible to change the URL while keeping the ability to perform a rolling upgrade so it is worth looking into this for 2.0-RC if there is time.  Rather than just updating the update end point I think it might be wise to rename the root of the URI to something like `internal_solr` so that it would be much harder for a Solr veteran to confuse Solr with Riak/Yokozuna.

**Comment by rzezeski** [comment]
One documented instance of confusion.  Though, this is not the first I have come across.

https://github.com/basho/riak/issues/545

**Comment by coderoshi** [comment]
@rzezeski I'll grab this. I'll also add a note to docs, warning against connecting to solr or using admin tools
