### ISSUE TITLE
indexes and schemas

### ISSUE THREAD

**Issue by sallespro** [basho/yokozuna#317]
hi, i have a couple of questions in my quest to master search with riak2.0.0pre15 and Solr

i have a bucket. i want to index every doc i insert using data that is in JSON format stored in the value.

so first i create an index, is  this `my_schema` is a xml file that has to be where ?

```
curl -i -XPUT http://localhost:8098/search/index/my_index \
  -H 'content-type: application/json' \
  -d '{"schema":"my_schema"}'
```

In this my_schema,  if my field is called FIELD, should it be FIELD_ss so that Yokozuna indexes it ?

```
<dynamicField name="*_ss" type="string" indexed="true" stored="true" multiValued="true"/>
```

**Comment by seancribbs** [comment]
You will need to upload the schema using the schema API, the command below should work:

``` shell
curl -i -XPUT http://localhost:8098/search/schema/my_schema \
    -H"Content-Type: application/xml" --data-binary @my_schema.xml
```

You can name fields whatever you like, but some field needs to match. The ones in the default schema use wildcards so that you don't have to make a schema for every new type of data. 

If you have fixed fields in your documents you can make a simpler schema that contains only those fields. Yokozuna has some required fields however, it might be best to simply copy those from the default schema.

**Comment by sallespro** [comment]
i see. it this is the defualt schema
https://github.com/basho/yokozuna/blob/v0.9.0/priv/default_schema.xml

the what are the "should match" or should be in place ones...?

if my data is 

```
{ "name" : "mr riaker", "age": 50, "city" : "Paris" }
```

as i understood i should have in my schema:

```
 <dynamicField name="name"  type="string"  indexed="true"  stored="true" />
 <dynamicField name="age"  type="tint"    indexed="true"  stored="true"/>

```

or alternatively, change my data fields to match the default prefixes

```
{ "name_s" : "mr riaker", "age_ti": 50, "city_s" : "Paris" }
```

**Comment by seancribbs** [comment]
In those cases, you can use regular fields. Dynamic fields allow wildcards and shouldn't be used if you know what the exact field name is. On the other hand, you could totally use the default schema with the last form you mentioned.

**Comment by seancribbs** [comment]
See also: http://wiki.apache.org/solr/SchemaXml

**Comment by sallespro** [comment]
the devil is in the details..

where does it expects to find the file...?

```
curl -XPUT http://localhost:8098/search/schema/syslogi -H'content-type:application/xml' --data-binary @default.xml
Error storing schema {fatal,{{invalid_name,[239,172,129,101,108,100]},
                             {file,file_name_unknown},
                             {line,3},
                             {col,2}}}
```

does in this single step shown before,  does it create the index and define it's schema or is it still necessary to do just the index creation ?

```
curl -XPUT -i 'http://localhost:8098/search/index/syslogi'
```

**Comment by rzezeski** [comment]
That looks to be an error parsing the XML. What are the contents of `default.xml`?

**Comment by sallespro** [comment]
```
<?xml version="1.0" encoding="UTF-8" ?>
<schema name="default" version="1.5">
 <ﬁelds>
    <ﬁeld name="kinds" type="string" indexed="true" stored="false" multiValued="true" />
    <ﬁeld name="originalMessage" type="text" indexed="true" stored="true" />
    <ﬁeld name="title" type="string" indexed="true" stored="true" />
    <ﬁeld name="score" type="int" indexed="true" stored="true" />
    <dynamicField name="*_ss" type="string" indexed="true" stored="true" multiValued="true"/>
    <ﬁeld name="_yz_ed" type="_yz_str" indexed="true" stored="false"/>
    <ﬁeld name="_yz_pn" type="_yz_str" indexed="true" stored="false"/>
    <ﬁeld name="_yz_fpn" type="_yz_str" indexed="true" stored="false"/>
    <ﬁeld name="_yz_vtag" type="_yz_str" indexed="true" stored="false"/>
    <ﬁeld name="_yz_node" type="_yz_str" indexed="true" stored="false"/>
    <ﬁeld name="_yz_rk" type="_yz_str" indexed="true" stored="true"/>
    <ﬁeld name="_yz_rb" type="_yz_str" indexed="true" stored="true"/> 
  </ﬁelds> 
</schema> 
```

**Comment by rzezeski** [comment]
You are using non ASCII for the `<fields>` tag.

**Comment by sallespro** [comment]
oops. strange pastes.

please let's go on considering the default_schema.xml which works, xml wise.

if i try to create the index/schema with this 

```
curl -XPUT http://localhost:8098/search/schema/sysy -H'content-type:application/xml' --data @default_schema.xml
```

this returns nothing. no error. nothing and if i try to

```
$ curl -XGET http://localhost:8098/search/index/sysy
```

nothing there.

But, if i just do

```
curl -XPUT http://localhost:8098/search/index/sysy
```

then after i can GET this which still indicates it is referring to `,"schema":"_yz_default"`

`{"name":"sysy","n_val":3,"schema":"_yz_default"}`

How can i correctly associate the xml file ?

**Comment by rzezeski** [comment]
The PUT returned nothing because there is no body. If you use the `-i`
option with curl it should show a 204 result for success.

The GET for the index returned nothing because the `sysy` index
doesn't exist. Once again, `curl -i` would show a 404 status.

The second PUT create the `sysy` index but no schema was specific so
it used the default.

To create an index and associate a schema you first upload the schema;
which you did correctly in this step:

```
curl -XPUT http://localhost:8098/search/schema/sysy -H'content-type:application/xml' --data @default_schema.xml
```

The second step is to create the index and pass a JSON request body
specifying the schema name to use:

```
curl -i -XPUT -H'content-type: application/json' http://localhost:8098/search/index/sysy -d '{"schema":"sysy"}'
```

Note that you'll want to delete the current `sysy` index first. The
PUT isn't smart enough to realize you've simply changed the schema.

```
curl -i -XDELETE 'http://localhost:8098/search/index/sysy'
```

**Comment by sallespro** [comment]
please take a closer look. it is not working as it should.

no schema gets created with this : 

`curl -XPUT http://localhost:8098/search/schema/sysy -H'content-type:application/xml' --data @default_schema.xml`

so if i try to GET to check wether the creation was successful

`curl -XGET http://localhost:8098/search/index/sysy`

There is nothing there.

So if i accept my fate, and do not try to create the schema with my own XML, is it possible to update once it was successfully, but not specifically, created with the _yz_default with the request below ?

`curl -XPUT http://localhost:8098/search/index/sysy`

**Comment by coderoshi** [comment]
You ARE getting a response back, just just aren't asking curl to show it to you. Curl, by default, hides header messages, which is where you can see whether your response was accepted or not. This is standard, classic, plain old fashioned HTTP and has nothing to do with Riak, per se.

So, if you want to see the response, add -i to your curl command, like "curl -i -XPUT ..."

If you want to see everything sent and received, add -v

Hope this helps,
Eric

**Comment by rzezeski** [comment]
> please take a closer look.

With respect, I think you should take a closer look at what I wrote.

Your schema was created. If you run with `-i` option you will see 204
returned. You can also use a GET on the schema resource to see the
schema content.

```
curl -i 'http://localhost:8098/search/schema/sysy'
```

The problem with YOUR get is that you are using the index
resource. There are two different resources at play here:
1. schema resource: /search/schema/{schema_name}
2. index resource: /search/index/{index_name}

(Not only did you use the wrong resource you used the wrong HTTP
method).

> is it possible to update once it was successfully, but not specifically, created with the yzdefault with the request below ?

No, you should not change the `_yz_default` schema. I don't think
Yokozuna would stop you but it's a bad idea.

Once again, the steps to add a schema and use the schema with an index:

```
curl -i -XPUT http://localhost:8098/search/schema/sysy -H'content-type:application/xml' --data @default_schema.xml

curl -i -XPUT -H'content-type: application/json' http://localhost:8098/search/index/sysy -d '{"schema":"sysy"}'
```

**Comment by sallespro** [comment]
what i mean with "there's nothing there" is not in regard to the curl response.

i mean the schema does not seem to be created.

**Comment by rzezeski** [comment]
What is the output of `curl -i 'http://localhost:8098/search/schema/sysy'`?

**Comment by sallespro** [comment]
dear zezeski. thanks for your samurai patience.

so, the problem seems to be with my carefullness trying to go step-by-step. 

this  GET 
`curl -i -XGET http://localhost:8098/search/index/sysy`

only returns anything after BOTH PUTS were in place. If you do the first PUT which seems to only upload the schema.xml and try to GET it you do not see anything until you really

```
curl -i -XPUT -H'content-type: application/json' http://localhost:8098/search/index/sysy -d '{"schema":"sysy"}'
```

**Comment by sallespro** [comment]
@rzezeski the output of 

```
curl -i 'http://localhost:8098/search/schema/sysy'
```

is the whole default_schema.xml, which i believe is corret.

**Comment by rzezeski** [comment]
> only returns anything after BOTH PUTS were in place. If you do the first PUT which seems to only upload the schema.xml and try to GET it you do not see anything until you really

Yes, this is why I asked you to read my original comment more carefully.

You must 1) upload the schema and then 2) create the index passing a JSON body with the name of the uploaded schema. Steps 1 & 2 are two completely different resources and they must be done in order.

It seems things are all cleared up now. Glad it's working.
