### ISSUE TITLE
mapreduce example at Riak2.0.0pre11 

### ISSUE THREAD

**Issue by sallespro** [basho/yokozuna#319]
i am following the Riak2.0.0pre11 search examples shown at 
http://docs.basho.com/riak/2.0.0pre11/dev/using/search/

the problem is with this mapreduce request returns [0] where it should be [3]

```
curl -XPOST "$RIAK_HOST/mapred" \
  -H'content-type:application/json' \
  -d '{"inputs":{"module":"yokozuna","function":"mapred_search","arg":["famous","NOT leader_b:true"]},"query":[{"map":{"language":"javascript","keep":false,"source":"function(v) { return [1]; }"}},{"reduce":{"language":"javascript","keep":true,"name":"Riak.reduceSum"}}]}'

```

**Comment by coderoshi** [comment]
This functionality actually works, it was my example in the docs that was incorrect. That is being fixed in future versions of the docs.

**Comment by sallespro** [comment]
how is the correct way to use it then ?

**Comment by coderoshi** [comment]
I'll post a link to the corrected doc once I push it.

**Comment by sallespro** [comment]
great. i can't help with the code, but maybe the docs... looking forward to it.

**Comment by sallespro** [comment]
hei, would you be so kind to just let me know how to do it ?

**Comment by coderoshi** [comment]
@sallespro sorry for the late reply, I hope you've seen the updated docs http://docs.basho.com/riak/2.0.0beta1/dev/using/search/
