### ISSUE TITLE
Storage requirement estimator for Search migrations

### ISSUE THREAD

**Issue by michellep-basho** [basho/yokozuna#343]
<b>Description</b>: Please provide a method to estimate the amount of storage required for a migration from legacy Search to the new Search (Yokozuna).

<b>Source:</b> customer via Zendesk
<b>Basho contact:</b> Dan Brown

**Comment by rzezeski** [comment]
What milestone should we set this for? This is a fairly fuzzy issue. Estimation will depend on the data. We could perform a simulated migration and measure relative differences in index size but that could be very data dependent and lead the user astray. I'm honestly not sure how to approach this. 

/cc @jonmeredith @gburd @coderoshi

**Comment by jonmeredith** [comment]
This is only going ot be an estimate.  If we have some search corpus you were comparing performance between the two systems, perhaps we could do some empirical measurement of the same data.

**Comment by rzezeski** [comment]
My point is that estimate could be misleading to users. I could run the fruit benchmark and maybe it will show a 45% difference between Yokozuna and Riak Search disk usage but then another dataset might be 15%. I'll do it though. We still need to decide a milestone and the requirements should be flushed out a bit more.

**Comment by jonmeredith** [comment]
The real milestone is when a paid production user really wants to know, but
ideally we'd have it for the 2.0 milestone (not RC).

On Mon, Mar 24, 2014 at 11:41 AM, Ryan Zezeski notifications@github.comwrote:

> My point is that estimate could be misleading to users. I could run the
> fruit benchmark and maybe it will show a 45% difference between Yokozuna
> and Riak Search disk usage but then another dataset might be 15%. I'll do
> it though. We still need to decide a milestone and the requirements should
> be flushed out a bit more.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/basho/yokozuna/issues/343#issuecomment-38476001
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by rzezeski** [comment]
I thought that there should be no 2.0 issues yet? I'll put it in 2.0-RC.

**Comment by rzezeski** [comment]
Do we still think there is time for this in 2.0-RC given other work that still needs to be done?

@jonmeredith @michellep @coderoshi

**Comment by lukebakken** [comment]
I'll be looking into this as well as documenting legacy search -> Yokozuna upgrades. Also see basho/basho_docs#1080

**Comment by lukebakken** [comment]
Some numbers using the default schema with legacy search and yz. `tweets.dat` has 65544 UTF-8 tweets from the `sample` public stream and is about 200MB in JSON data.

```
# du -hs tweets.dat
202M    tweets.dat
```

Riak 1.4.8 data directory sizes:

```
# du -hs /var/lib/riak/*
30M     /var/lib/riak/anti_entropy
2.0G    /var/lib/riak/bitcask
36K     /var/lib/riak/kv_vnode
2.8G    /var/lib/riak/merge_index
8.0K    /var/lib/riak/ring
```

Riak 2.0.0beta1 data directory sizes:

```
# du -hs /var/lib/riak/*
42M     /var/lib/riak/anti_entropy
682M    /var/lib/riak/bitcask
76K     /var/lib/riak/cluster_meta
40K     /var/lib/riak/generated.configs
36K     /var/lib/riak/kv_vnode
4.0K    /var/lib/riak/riak_kv_exchange_fsm
8.0K    /var/lib/riak/ring
137M    /var/lib/riak/yz
20M     /var/lib/riak/yz_anti_entropy
```

Note: I determined that disabling legacy search in Riak 1.4.8 will result in `/var/lib/riak/bitcask` using about the same space as in Riak 2.0.0beta1.

**Comment by rzezeski** [comment]
Nice to see Solr using ~4.8% of the size that merge index requires for the same indexing.  That will vary depending on how you configure your Solr schema, but very nice to see none the less.

> Note: I determined that disabling legacy search in Riak 1.4.8 will result in /var/lib/riak/bitcask using about the same space as in Riak 2.0.0beta1.

The reason you see more bitcask usage with legacy search is because it writes "proxy objects" for the index entries in merge index.  It needs to do this in order to delete the index entries when the KV object is deleted.  Yokozuna doesn't need these special proxy objects so it saves even more space and time.

**Comment by lukebakken** [comment]
@rzezeski - thanks for the explanation for legacy search.

**Comment by lukebakken** [comment]
2.0.0beta1 run using a custom schema (most fields unindexed, `text` field indexed _and_ stored):

```
# du -hs /var/lib/riak/*
46M     /var/lib/riak/anti_entropy
680M    /var/lib/riak/bitcask
88K     /var/lib/riak/cluster_meta
40K     /var/lib/riak/generated.configs
36K     /var/lib/riak/kv_vnode
4.0K    /var/lib/riak/riak_kv_exchange_fsm
8.0K    /var/lib/riak/ring
34M     /var/lib/riak/yz
19M     /var/lib/riak/yz_anti_entropy
```

Schema: https://github.com/lukebakken/riak-data-loader/blob/master/twitter-schema.xml

**Comment by lukebakken** [comment]
2.0.0beta1 run using a different custom schema that indexes _and_ stores every value in the tweet JSON:

```
du -hs /var/lib/riak/*
44M     /var/lib/riak/anti_entropy
678M    /var/lib/riak/bitcask
88K     /var/lib/riak/cluster_meta
40K     /var/lib/riak/generated.configs
36K     /var/lib/riak/kv_vnode
4.0K    /var/lib/riak/riak_kv_exchange_fsm
8.0K    /var/lib/riak/ring
99M     /var/lib/riak/yz
20M     /var/lib/riak/yz_anti_entropy
```

Note that only 99M is used as opposed to 137M above, due to booleans and ints being stored with specific types as opposed to strings.

**Comment by lukebakken** [comment]
Indexing `wiki-small.tar.gz` html files from http://www.search-engines-book.com/collections/ using default legacy search schema and modified `_yz_default` schema in 2.0 that indexes and stores everything (`text/plain` content type):

1.4.8:

```
# du -hs /var/lib/riak/*
3.3M    /var/lib/riak/anti_entropy
1.5G    /var/lib/riak/bitcask
36K     /var/lib/riak/kv_vnode
3.2G    /var/lib/riak/merge_index
12K     /var/lib/riak/ring
```

2.0.0beta1:

```
# du -hs /var/lib/riak/*
3.9M    /var/lib/riak/anti_entropy
445M    /var/lib/riak/bitcask
92K     /var/lib/riak/cluster_meta
40K     /var/lib/riak/generated.configs
36K     /var/lib/riak/kv_vnode
4.0K    /var/lib/riak/riak_kv_exchange_fsm
8.0K    /var/lib/riak/ring
275M    /var/lib/riak/yz
2.9M    /var/lib/riak/yz_anti_entropy
```

**Comment by jonmeredith** [comment]
Closing this as further work is covered in basho/basho_docs#1095. TYVM.
