### ISSUE TITLE
Custom extractor

### ISSUE THREAD

**Issue by sendtopms** [basho/yokozuna#346]
Is there a way to configure custom extractor? I have a custom proplist binary document stored in riak which i want to index, any suggestion how to do it without custom extractor.

**Comment by coderoshi** [comment]
You'll need to write an extractor (there are a few examples to look at https://github.com/basho/yokozuna/blob/develop/src/yz_text_extractor.erl). Then compile the beam and add it to each of your nodes http://docs.basho.com/riak/latest/ops/advanced/install-custom-code/. Finally, you'll have to register the extractor module (eg `custom_proplist_extractor`) with a custom mime-type (eg. "application/proplist") on every node.

```
yz_extractor:register("application/proplist", custom_proplist_extractor).
```
