### ISSUE TITLE
sort without score, bug? [JIRA: RIAK-1696]

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#372]
A user on the mailing list was not able to sort unless the `score` field is included in the field list.  If this is true it seems like a bug to me.

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-May/015203.html

**Comment by bfitzsimmons** [comment]
This has hit me as well.  Fortunately the user who brought it up on the list told me of the workaround.

**Comment by DSomogyi** [comment]
Comment for Jira.
