### ISSUE TITLE
rpc:call try/catch rex

### ISSUE THREAD

**Issue by joedevivo** [basho/yokozuna#373]
```
/Users/joe/dev/basho/riak_ee/deps/yokozuna/src/yz_kv.erl:
  166  -spec has_indexes(node()) -> boolean().
  167  has_indexes(RemoteNode) ->
  168:     RemoteIndexes = case rpc:call(RemoteNode, yz_solr, cores, [], 5000) of
  169          {ok, Indexes} -> Indexes;
  170          _ -> error

/Users/joe/dev/basho/riak_ee/deps/yokozuna/src/yz_solr.erl:
  278  -spec host_port(node()) -> {string(), string() | unknown}.
  279  host_port(Node) ->
  280:     case rpc:call(Node, yz_solr, port, [], 1000) of
  281          {badrpc, Reason} ->
  282              ?DEBUG("error retrieving Solr port ~p ~p", [Node, Reason]),
```

**Comment by joedevivo** [comment]
https://gist.github.com/reiddraper/7955381dc1fecf552220

**Comment by rzezeski** [comment]
`yz_solr:host_port/1` is fine as is.  It is called by the cover server or directly by a client request so if it crashes no biggie.

`yz_kv:hash_indexes` is called by `yz_kv:should_handoff` which runs on the `riak_kv_vnode` process.  So it could crash the vnode in the rare case of rex crashing.  But I would argue not to make the change as there are other things that can crash the KV vnode that are more likely.  Also, the `should_handoff` function needs to change to do all it's work in it's own process and that way the only thing done on the vnode is to check either shared global state like ETS or make a call to another process to determine if it may proceed to handoff.  In that case the try/catch for this rare rex case is definitely not needed.

@joedevivo So I would say lets not bother with the defensive programming in Yokozuna.

**Comment by joedevivo** [comment]
I respect your opinion. let's close it down.
