### ISSUE TITLE
Query returns 3 results for single doc

### ISSUE THREAD

**Issue by JohnDMathis** [basho/yokozuna#374]
I have a bucket containing only a single document.  When I query for the document `(*:*)` I get back 3 results:

```
"docs": [
      {
        "id": "00008jauh0rGJAoDDixz6G",
        "_yz_id": "default_test_00008jauh0rGJAoDDixz6G_13",
        "_yz_ed": "1 13 default test 00008jauh0rGJAoDDixz6G g2IAEmxK",
        "_yz_fpn": "13",
        "_yz_pn": "13",
        "_yz_rk": "00008jauh0rGJAoDDixz6G",
        "_yz_rt": "default",
        "_yz_rb": "test"
      },
      {
        "id": "00008jauh0rGJAoDDixz6G",
        "_yz_id": "default_test_00008jauh0rGJAoDDixz6G_14",
        "_yz_ed": "1 14 default test 00008jauh0rGJAoDDixz6G g2IAEmxK",
        "_yz_fpn": "13",
        "_yz_pn": "14",
        "_yz_rk": "00008jauh0rGJAoDDixz6G",
        "_yz_rt": "default",
        "_yz_rb": "test"
      },
      {
        "id": "00008jauh0rGJAoDDixz6G",
        "_yz_id": "default_test_00008jauh0rGJAoDDixz6G_15",
        "_yz_ed": "1 15 default test 00008jauh0rGJAoDDixz6G g2IAEmxK",
        "_yz_fpn": "13",
        "_yz_pn": "15",
        "_yz_rk": "00008jauh0rGJAoDDixz6G",
        "_yz_rt": "default",
        "_yz_rb": "test"
      }
    ]
```

In our application the **id** field is unique, but based on several things I've read and heard, we set the unique key in the schema to **_yz_id**.  We tried setting the unique key to **id**, and it appeared to resolve this issue just fine. _Is it ok to use a different value for the unique key? If not, why are we getting 3 docs back instead of just one? How do we prevent this?_

**Comment by rzezeski** [comment]
@JohnDMathis It looks like you queried the Jetty/Solr HTTP port.  You
**DO NOT** want to query this port, you need to query the Riak HTTP
port so that Yokozuna can run a proper distributed query.

Also, **NEVER** change the unique id.  It must be `_yz_id` or bad
things will happen for clusters that don't have all replicas on unique
nodes (such as 1-3 node clusters with n=3).

**Comment by JohnDMathis** [comment]
Thanks. I was indeed experimenting with queries using the solr UI. Appreciate the prompt reply.

**Comment by JohnDMathis** [comment]
Sorry, one quick follow up: we're using solr-client.js, which hits **host:8093/solr/test_index**.  It sounds like we should not be using this, is that correct?

**Comment by coderoshi** [comment]
@JohnDMathis Correct. when you connect to riak search, you must connect through the Riak port, which defaults to `8098`.
