### ISSUE TITLE
range facets with mincount inconsistent [JIRA: RIAK-1694]

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#378]
Note: This issue is based off an index card I wrote nearly a year ago
so I don't have an exact example but it should be easy to reproduce if
still an issue.

While building a RICON demo I noticed that setting `facet.mincount` to
1 during a range facet produced inconsistent results across queries
(when the query plan changes).  I believe the cause to be that
mincount is applied to each shard separately rather than for the
combined result.

Attempt to reproduce and determine the root cause.  A fix may require
a patch to Solr upstream.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by zeeshanlakhani** [comment]
@jvoegele as part of #571 / #530, can you test this?

**Comment by zeeshanlakhani** [comment]
@JeetKunDoug @jvoegele this has not be tested in #571 yet... will be added as a separate pr.

**Comment by zeeshanlakhani** [comment]
closing as per #627.
