### ISSUE TITLE
Ambiguous HTTP resource

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#383]
If a user creates the and index named `index` then they will not be
able to query it via HTTP because the `/search/index` resource is
being used by `yz_wm_index`.  The two solutions I see are:
1. Disallow an index named `index`.
2. Move the `yz_wm_search` route to `/search/query/IndexName`.

I think the second is cleaner and more consistent.  Though I'm sure
it's not very RESTful (I admit I don't understand how to make good
HTTP APIs).  In any case something has to be done and option (1) seems
like a poor choice.

ping: @coderoshi @seancribbs

**Comment by dmitrizagidulin** [comment]
Of the two options, I'd vote for 2), but what about a third option:
3. Use existing Solr convention of `/search/IndexName/select` ?

**Comment by coderoshi** [comment]
I'm down with 2

**Comment by dmitrizagidulin** [comment]
The reason I mention following existing Solr url conventions, is because for many of the non-official Riak client libraries (that don't have PB support), when I asked the maintainers what their plans for 2.0/Search support were, they inevitably say "Well, no sense in reinventing the wheel, we'll just tell people to use existing Solr clients".  And so to that end, it might make sense to make that task as easy as possible. (Or at least support the Solr APIs as a rewrite rule / behind-the-scenes option).

**Comment by coderoshi** [comment]
But `/solr/core/select` is already supported. You can use solr clients today.

**Comment by dmitrizagidulin** [comment]
@coderoshi ah, ok, thanks!

**Comment by seancribbs** [comment]
@coderoshi @rzezeski Any reason for the other URL then?

**Comment by rzezeski** [comment]
> @coderoshi @rzezeski Any reason for the other URL then?

Just because it was around before but perhaps we should get rid of it while we can?  Actually, before it was not ambiguous because `/yz` was the root.  So it was `/yz/search` for queries and `/yz/index` for index admin.  But then we renamed the root to `/search` because REASONS and `/search/search` looked weird so here we are with an ambiguous resource.

In any case, I'd say the two options are now:
1. Rename to `/search/query/Index`.
2. Remove `search/Index` route and just use the `/solr/Index/select` resource.

**Comment by coderoshi** [comment]
@rzezeski @seancribbs If this is going to happen, it should happen now before RC. We also have a lot of documentation to update in response, as well at the http Python and Erlang client.

**Comment by rzezeski** [comment]
@coderoshi Working on this now.  I'm removing the `/search/Index` resource.  The `/solr/Index/select` resource works just the same, matches legacy search, and works with existing Solr clients.

**Comment by rzezeski** [comment]
@coderoshi Of course, right after I choose a solution I realize it causes problems for migration.  If both legacy and new search use the same HTTP resource then there is no way to query new search to make sure migration has succeeded before switching over HTTP/PB control.  We could require migrating users to attach to Riak to run test queries before switching control, or name the resource `/search/query/Index`.  Guess I'll go with the later.

**Comment by coderoshi** [comment]
@rzezeski that's good, I was voting for the later anyway. If yokozuna is ever going to support other indexing engines like ES, it doesn't help getting too hung up on how Solr does things.
