### ISSUE TITLE
Better Index/Schema Administration [JIRA: RIAK-1688]

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#403]
This is a dump of the ideas I have for better index/schema
administration in Yokozuna.
## Current State of Affairs

The current schema and index administration APIs mostly work but allow
too many ways for users to shoot themselves in the foot.  Many users
have already found the API complex and awkward.

Both HTTP and PB allow the storing and modification of schemas.  A
schema is a name along with a blob of XML.  This XML will be handed
off to Solr verbatim.

A user may also create and delete indexes over HTTP or PB.  When
creating an index an N value and schema name may be supplied.  If no
schema is specified the built in default is used named `_yz_default`.
## Steps During Index Creation

This is an overview of the steps taken by Yokozuna during index
creation.  Index creation is async and proceeds in two stages.  The
first is the user request and the second is the creation of the Solr
Cores across the cluster (in Solr, indexes are called Cores).
### user request
1. If the index already exists then just return success, otherwise
   proceed.
2. If the schema exists then proceed, otherwise return an error saying
   the schema doesn't exist.
3. Write an entry to cluster-meta for the index.
4. Return success.

See: `yz_wm_index:maybe_create_index`, `yz_pb_admin:maybe_create_index`, `yz_index:create`
### core creation

Every node has an event server with a periodic tick upon which it
performs various tasks including checking the cluster-meta for new
index entries.  This is the `yz_events` server, the name comes from
the days when Yokozuna used ring events for notification which it no
longer does.

Remember, these steps are occurring on _each_ node, even the one that
serviced the user request.
1. Tick fires.
2. If Solr is up and either a) the cluster-meta hash for yz indexes
   changed or b) this tick represents a "full check" then continue.
3. Grab the list of cores from the local Solr node.
4. Grab the list of indexes from the cluster-meta.
5. Calculate a delta of removed, added and those that stayed the same.
6. Remove indexes that were removed.
7. Combine the added and same, for any that don't exist try to create
   them locally and continue to next step.
8. Create the directory structure needed under data dir and copy
   various files, including the schema file and `solrconfig.xml`.
9. Send a request to Solr to create the core.  Log return from Solr,
   whether success or failure.

Since this second stage is based on a tick per node that means that a)
the actual local creation of the core may occur at different times
across and cluster, b) core creation is async from the user request
and c) if a core creation fails it will retry to infinity until the
failure is fixed (normally this comes in the form of a bad schema).

See: `yz_events:handle_info(tick, S)`, `yz_events:sync_indexes`, `yz_index:local_create`
## Issues

Here are some issues I see with the schema/index administration as it
stands now.
- User must understand Solr schema syntax completely.
- User must remember to add special Yokozuna fields (`_yz_*`).
- User cannot easily reload a schema across the cluster.
- Index creation is async, there is no simple way for a user to
  determine if index creation was successful across the entire
  cluster.
- Indefinite retry of index creation when schema is bad.  (No, you
  cannot fully verify the schema because the spec is too loose and
  their is no Solr API to verify.)
- A different version of the schema may be used across cores if the
  user modifies the schema of an existing index and then adds a new
  node without first reloading the index.
- No way to verify that a schema will work without creating and then
  deleting the index.
- No "schemaless" mode which users love so much even though it is a
  gimmick.
## Proposal

Here are some of my ideas for a better administration interface.
### rip out HTTP/PB admin

Remove all HTTP/PB administration APIs except maybe for the ability to
retrieve information.  But definitely no modification allowed.  Trying
to make a robust administration over these protocols is annoying and
error prone.
### add 'riak-admin search index' command

There is already a `riak-admin search` command.  Add an `index`
subcommand for administering indexes along with their schemas.  That
is, there will be no separate administration for schemas.  The two
will be one.  This removes all the complexity around deleting schemas
in the current system.  If each index has its own internal schema then
the problem of deleting/modifying a schema simply doesn't exist.  It
also means one less API and semantic to define.

All administration of indexes must go through the command line client.
There will be no PB/HTTP/etc channels.  Index creation should almost
never be scripted in production anyways.  For scripting in test
scenarios (e.g. Riak Test) the internal Erlang APIs may be used.
### synchronous + idempotent creation

Index creation should be synchronous to the user.  No more two stage
nonsense where the user has to play games querying all the nodes to
determine if an index was created successfully.  Creation should also
be idempotent.  If the creation fails on some nodes then the user can
retry without fear of damaging the existing cores.
### two-phase creation

Index creation should be like node join/remove.  It should be split
into the plan/test phase and a commit phase.
1. Create an index with the minimal base schema.
2. Add some fields.
3. Write some test documents and perform queries.
4. If happy with the results then 'commit' the index which will
   actually create it across the cluster.

When a user initially creates an index Yokozuna will create a
temporary index on the local node only.  The user can then index Riak
objects in this index directly without associating a bucket and run
queries to verify things are working.  When they are satisfied the
index is committed which will delete the temporary index and create
the final one across the entire cluster.  This allows users to tune
the index inside of a sandbox before creating it across the entire
cluster.
### "schemaless" mode

First off, "schemaless" mode is a gimmick (both in Solr and
ElasticSearch).  You essentially start with a blank schema and as data
is written fields are automatically defined on that schema.  Users
like it because they don't have to think.  The problem is that the
computer thinks for them and unfortunately it picks the lowest common
denominator when it comes to field types.  Efficient search is all
about picking the appropriate types and analyzers.  Users should never
use "schemaless" mode in production.

That said, it can be useful in development while trying to figure out
an initial schema.  I think it would be nice to have the ability to
put an index in "schemaless" mode in the planning stage so that it can
aid the user in creating a schema.  I envision the steps as so:
1. Create an index with the minimal base schema and pass the
   `--schemaless-mode` option.
2. Insert some data.
3. Ask the index for it's current schema.
4. Abort that index.
5. Tweak the schema in step 3 with help from someone that understands
   Solr/Lucene.
6. Create an index passing in the schema from step 5.
### all schema interaction via cmd line

Users will no longer deal directly with Solr schemas; no more hand
editing of XML (except for escape hatch for "experts").  Creating a
schema can be a daunting task for those not familiar with Solr.  It's
also very easy to mess up because of the lack of ability to verify a
schema before creating the index.  A simple typo can cause issues that
only show up after creating the index.

Provide an interface under the `index` subcommand for adding fields to
the schema of an index.  Not only does this avoid learning the XML but
it prevents basic mistakes from being made like adding the same field
twice (which will cause a runtime error) or spelling a Java class name
incorrectly.  Frankly, it gives us, the Riak devs, more control over
how users build their schemas.
### provide base schemas

Rather than force users to always add all fields provide some base
schemas to use.
- full: The same as today's default schema.
- suffix: Remove a lot of the language analysis stuff but keep the
  dynamic fields.
- minimal: Only the fields required by Yokozuna.  All other base
  schemas must be supersets of this one.

These are just ideas for base schemas.  Another idea is base schemas
per spoken language supported by Solr.  For example, Russian,
Japanese, German, etc.
## Command Synopsis

```
riak-admin search index <op> [args]
```

Create an index:

```
riak-admin search index create <name> [-n <n_val>] [-b <base_schema_name>] [-s|--schemaless] ...
```

Add a field:

```
riak-admin search index add-field <name> <type> [-s|--stored] [-r|--required] [-i|-indexed] [-m|--multi-valued] ...
```

Add a field type:

```
riak-admin search index add-field-type <name> <class> [-sm|--sort-missing-last] [-ps|--precision-step <int>] [-pig|--position-increment-gap <int>] [-i|--indexed] ...
```

Commit an index

```
riak-admin search index commit <name>
```

Abort an index

```
riak-admin search index abort <name>
```

Delete an index (which has been committed, maybe just use delete for abort as well?)

```
riak-admin search index delete <name>
```

Keep in mind this is a straw man synopsis.  The point is that
index/schema creation would become a more controlled act versus the
free-for-all that is is now.
## Mutating Schemas

Mutating schemas is a very tricky thing.  Once an index has data in it
you are very limited in the schema mutations you can make.  Basically,
the only safe thing is to add fields or field types.  You cannot do
things like change the type of a field or the class name of a type.
That will cause queries and other processes to fail.  Even if you only
add fields that does not mean that all previous indexed objects will
be queryable under that field.  Action will have to be taken to
reindex those objects to pick up that new field.

Since Solr has APIs for swapping cores atomically I think some work
could be done on the Yokozuna side to make mutations possible (but
probably expensive).  You could extend the index subcommand to allow
mutations.  It would once again be a multi-phase, plan/commit/abort,
thing.  If the user commits the changes then Yokozuna will stand up a
hidden core across the cluster and start reindexing all the objects in
the background.  Once that background job completes the user will be
able to choose to swap the new for the old.  This allows incoming
queries to be serviced by the old index while the new one is being
built.  Incoming writes will have to go to both the old and new index
so there will be some write amplification during this time along with
the background process.

**Comment by xpe** [comment]
This is a nice write-up. I agree with much of it.

I can understand your frustration here; I've spent quite a bit of time writing [a Clojure driver for Riak 2.0.0 for the Protocol Buffer interface](https://github.com/bluemont/kria). Setting up tests involves lots of step-by-step polling. First create a schema. Then an index. Then you can create a bucket. This is the nature of how Solr works; I don't see obvious ways of getting around it.

I like your suggestion of a synchronous schema and index creation option.

I'm _not_ a fan of the "ripping out" suggestion:

> Remove all HTTP/PB administration APIs except maybe for the ability to
> retrieve information. But definitely no modification allowed. Trying
> to make a robust administration over these protocols is annoying and
> error prone.

So drastic! That solution would be worse than the problem. Having schema and index features available via the wire APIs is very important.

I'd argue we need _more_ cluster-oriented wire APIs: I _would_ like to see wire API calls that would tell me when schemas and indexes are ready, across the cluster.

I'd also like to see an API call that could give me cluster status: what nodes are connected and so on.

**Comment by marksteele** [comment]
+1 on everything here. 

I agree that making schema changes via the CLI is the way to go. Makes it easier to integrate things like configuration management.

About mutating schemas, it's a tough problem. I think the atomic swap/write to both is probably the right answer.

**Comment by andrewzeneski** [comment]
I agree with @xpe, I too would love to see more wire APIs; losing the ability to create indices (and/or attaching them to a bucket) on demand from the API would be a serious show stopper for me. That said, post index creation schema management from the APIs isn't as much of an issue [for me]. 

I am actually a fan of the current separation of index and schema. I often re-use the same schema for many indices that require segregation for other reasons. I'd like to see this expanded rather than abandoned. This seems like the logical place to keep schema versions.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by binarytemple** [comment]
+1 for this feature

**Comment by mogadanez** [comment]
does it any technical stops to have several search indices on a bucket? it can simplify migration between schemas.

**Comment by zeeshanlakhani** [comment]
Closing this in favor of keeping everything in https://github.com/basho/yokozuna/issues/130, including this note.
