### ISSUE TITLE
Bitcask expiration

### ISSUE THREAD

**Issue by lukebakken** [basho/yokozuna#412]
Version tested: `2.0.0rc1`

Since bitcask expiration is a backend feature, there is no way for it to update YZ data when objects expire. AAE will eventually do it but I hope there are plans to make expiration more "first class" within Riak to resolve this.

**Comment by rzezeski** [comment]
If you didn't see it already: https://github.com/basho/yokozuna/blob/develop/docs/Q-AND-A.md#how-does-yokozuna-deal-with-bitcask-expiry

**Comment by lukebakken** [comment]
@rzezeski thanks for the link. I'll reference it in the docs issue.
