### ISSUE TITLE
facet.pivot options not proxied to internal solr [JIRA: RIAK-1683]

### ISSUE THREAD

**Issue by mogadanez** [basho/yokozuna#424]
http://localhost:8098/search/query/some_index?q=_:_&wt=json&facet=true&facet.pivot=f1,f2,f3&rows=0

=>

```
facet_counts: {
facet_queries: { },
facet_fields: { },
facet_dates: { },
facet_ranges: { }
}
```

http://localhost:8093/internal_solr/some_index/select?q=_:_&wt=json&facet=true&facet.pivot=f1,f2,f3&rows=0

=>

```
facet_counts: {
facet_queries: { },
facet_fields: { },
facet_dates: { },
facet_ranges: { },
facet_pivot: {
f1,f2,f3: [
{
field: "f1",
value: "lJa--e5W6lkx6b-gq-6",
count: 134,
pivot: [
{
field: "f2",
value: "94ed4664ef6b4a35b4e8b5542d2b383e",
count: 122,
pivot: [
...
```

**Comment by coderoshi** [comment]
I'm afraid you found one of the limitations of DistributedSolr, which we are bound by. DistributedSolr, doesn't support joins or pivot faceting: https://wiki.apache.org/solr/DistributedSearch#Distributed_Searching_Limitations

**Comment by mogadanez** [comment]
seems it fixed in latest version
https://issues.apache.org/jira/browse/SOLR-2894

Since SOLR is separate system, does it possible to use different version?

**Comment by coderoshi** [comment]
We haven't updated to the newest version of Solr, since it was too close to the 2.0 release date. You can try upgrading the version in each of your nodes, but there's no guarantee that everything will work the same, or even at all. We'll be upgrading to the newest Solr in an upcoming version.

**Comment by rzezeski** [comment]
> Since SOLR is separate system, does it possible to use different version?

Unfortunately, no.  I mean, technically it is possible, but it requires a custom build.  Yokozuna uses its own custom build of Solr and needs the solrconfig.xml configured a certain way.  It has both directly applied patches to the distributed search code as well as custom components for AAE and to handle system shutdown.  I have instructions for a custom build written up somewhere that you could try but be warned you would be running a one off environment that would lock you into having to do a custom build for every Riak release.  It could get really ugly from an operations perspective.

**Comment by mogadanez** [comment]
It ok to wait for me.
Yokozuna is really big step forward and just appetite  comes with eating
and wanted use full potential. But anyway curent set of features give
ability to improve my code a lot.

понедельник, 13 октября 2014 г. пользователь Ryan Zezeski написал:

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by zeeshanlakhani** [comment]
Need to test this as part of #490

**Comment by zeeshanlakhani** [comment]
Closing this w/ updates to be found in #531
