### ISSUE TITLE
Docs Lost in Handoff [JIRA: RIAK-1609]

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#426]
When a node leaves a cluster, some indexed documents are not completely transferred. This can be easily replicated by creating a 5 node cluster, setting up an index on a bucket and populating it with 10k objects. Then verify that the `numFound` returned on a query equal the bucket list count. Next, make one of the nodes leave, and query the `numFound` again. The number is often less than 10k.

``` bash
#!/bin/bash

curl -XPUT "http://localhost:10018/search/index/test_index"
echo "Sleeping for index to propogate"
sleep 5
curl -XPUT "http://localhost:10018/buckets/test_bucket/props" -H'content-type:application/json' -d'{"props":{"search_index":"test_index"}}'
echo "Sleeping for props to propogate"
sleep 1

echo "Populating 10k objects"
for (( i=1; $i <= 10000; i++ )) ; do
curl -XPUT "http://localhost:10018/buckets/test_index/keys/key$i" -H'content-type:application/json' -d'{"datastore": {"id":" '"$i"'"}}'
done

# Both values should be 10k, but they may not be after a node leaves
expr `curl -XGET "http://localhost:10018/buckets/test_bucket/keys?keys=true" 2>/dev/null | json_pp | wc -l` - 4
curl -XGET "http://localhost:10018/solr/test_index/select?wt=json&q=*:*" 2>/dev/null | json_pp | grep numFound | sed "s/[^0-9]//g"
```

You can verify this another way, by just querying the total number of replicated values (should be 30k---after leaving a node the result is fewer, from a dozen to hundreds).

```
http://localhost:10014/internal_solr/test_index/select?q=*:*&wt=json&shards=127.0.0.1%3A10014%2Finternal_solr%2Ftest_index%2C127.0.0.1%3A10024%2Finternal_solr%2Ftest_index%2C127.0.0.1%3A10034%2Finternal_solr%2Ftest_index%2C127.0.0.1%3A10044%2Finternal_solr%2Ftest_index%2C127.0.0.1%3A10054%2Finternal_solr%2Ftest_index
```

Surprisingly, attempting to replicate this failure using riak_test doesn't work (no theories as to why, yet). The handoff tests function flawlessly, and an attempt to replicate the above using regular riak_test functions return 10k `numFound` every time. So we wrote an r_t that executed an external script which runs curl, and the problem surfaces again.

**Comment by zeeshanlakhani** [comment]
For reference: [r_t](https://github.com/basho/riak_test/blob/er-yz-handoff/tests/yz_handoff.erl) that runs the [external script](https://github.com/basho/riak_test/blob/er-yz-handoff/handoff-test.sh)

**Comment by zeeshanlakhani** [comment]
11/18/14's related notes -> https://gist.github.com/zeeshanlakhani/40bd3f54ee95ead1aad9.

**Comment by zeeshanlakhani** [comment]
related issue/notes from @ksauzz: https://gist.github.com/ksauzz/13e8f064b9744f1d06b0

**Comment by Basho-JIRA** [comment]
Fixed in 2.1, appears related to problems with entropy data and yz_events. 

**_[posted via JIRA by Sean Cribbs]**_

**Comment by ksauzz** [comment]
yay! :+1:

**Comment by zeeshanlakhani** [comment]
We may have found the actual culprit, but will reopen w/ a more specific ticket. 

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love |
twitter => @zeeshanlakhani
