### ISSUE TITLE
define custom extractor

### ISSUE THREAD

**Issue by binarytemple** [basho/yokozuna#433]
Say I have some weird format that I store my objects in, lets say protocol buffer encoded as an example.

I've found an example of an extractor [yz_json_extractor.erl](https://github.com/basho/yokozuna/blob/919fad4d7c3e457be7d31de96db42be4907f7a08/src/yz_json_extractor.erl)

And I've found where extractors are mapped by content-type in [yz_extractor.erl](https://github.com/basho/yokozuna/blob/47214a66e07fdfd04bbaae6bdd18580f87693edf/src/yz_extractor.erl#L31)
- How can I add a new content-type to custom extractor mapping without submitting a PR ? 
- Is it possible to pass extraction through to Solr, so I could write my extractor in Java?

**Comment by binarytemple** [comment]
@lucperkins this might be something for documentation if it is possible

**Comment by binarytemple** [comment]
Some further information (thanks @angrycub )

It is possible (via riak attach to register a custom extractor using `yz_extractor:register(MimeType, Def)`

The MimeType/extractor map is stored into the yz ring metadata.

From then on, it's in the ring, so it would be read on system startup.

One caveat, there doesn't appear to be a way to un-register an extractor - you can change it, but not delete it, at least not without modifying the ring-file.

**Comment by zeeshanlakhani** [comment]
@binarytemple yep, there's no unregister fn as of yet. Maybe this is something we can add, as it should be easy enough. Will talk to @coderoshi about it.

**Comment by coderoshi** [comment]
As for "unregistering" an extractor, you can just redefine its extract function to the noop extractor.

**Comment by zeeshanlakhani** [comment]
@coderoshi good point.
