### ISSUE TITLE
Timeouts during bulk data load, possible tie in to yz_events crash and a bad state on core create

### ISSUE THREAD

**Issue by lukebakken** [basho/yokozuna#442]
Customer ticket 9698

During a bulk data load of about 10 million objects, timeouts occur:

> This week we had a total of 196 errors logged during the bulk import.
> 3 handle_info crash reports (9 messages) 
> 19 iterate_entropy_data req_timeout 
> 167 failed to index object

Issue #367 details benchmarking and work done to improve Riak <-> Solr communication, concluding with a note that further investigation and work needs to be done. I'm opening this issue to indicate further benchmarking and work needs to be done to improve performance.

**Comment by rzezeski** [comment]
In case you didn't see it in the mess, ibrowse is horrible. Hacking its load balancer to not be dumb would help.

https://github.com/basho/yokozuna/issues/330#issuecomment-40783996

A fair number of perf-labeled issues that would reduce indexing latency. Plenty of low-hanging fruit.

**Comment by zeeshanlakhani** [comment]
@lukebakken did this include any errors related to yz_events:handle_info or anything related to `*already_exists` or `couldn't create index` errors in the solr/console logs?

**Comment by lukebakken** [comment]
@zeeshanlakhani yes all of those errors are present (https://basho.zendesk.com/agent/tickets/9698)

**Comment by zeeshanlakhani** [comment]
Cool... @lukebakken, just making sure it's all the same, as it may not be explicitly related to ibrowse/solr not keeping up w/ load then... due to the other failures.
