### ISSUE TITLE
one entry in riak, duplicate docs in Solr

### ISSUE THREAD

**Issue by maghbari** [basho/yokozuna#443]
Hello,
I facing an issue in which I am using riak-java-client to add docs to Riak and query them using solr through Yokozuna Api... The problem I face is that when I add one doc to riak I find 3 duplicate entries in solr...
an example of the java code I use it:::

``` java
            MediaFingerprint media = new MediaFingerprint();
            media.song_id = "track-4";
            media.song = "Bailamos";
            media.artist = "Enrique";
            media.album = "unknown";
            media.length = 250;
            media.import_date = "NOW";


            Namespace mediaBucket = new Namespace("media_data_store","media");
            Location mediaLocation = new Location(mediaBucket, "track4");
            StoreValue storeMediaOp = new StoreValue.Builder(media).withLocation(mediaLocation).build();
            client.execute(storeMediaOp);
```

And when I query the song ID in solr I got this solr

``` json
            "response": {
            "numFound": 3,
            "start": 0,
            "docs": [
              {
                "song": "Bailamos",
                "artist": "Enrique",
                "song_id": "track-4"
              },
              {
                "song": "Bailamos",
                "artist": "Enrique",
                "song_id": "track-4"
              },
              {
                "song": "Bailamos",
                "artist": "Enrique",
                "song_id": "track-4"
              }
```

I am really sure that I have all clusters and clients shutdown after addition, and I have no bad loops and such things...
Thanks,,,

**Comment by maghbari** [comment]
I have also tested the same entry with http curl and still having the duplicates...

**Comment by coderoshi** [comment]
How are you querying? Ensure you're querying /solr/ and not /solr_internal/. Also, solr admin tools don't work with yokozuna.

**Comment by maghbari** [comment]
Thanks Eric, you are right I am querying /solr_internal... so do I need to query solr through Riak client?? Can't I access solr directly??

**Comment by zeeshanlakhani** [comment]
@maghbari are you still having this issue? The Riak Java Client won't let you explicitly call into the /solr/ side.
