### ISSUE TITLE
Add 'search_query_latency_mean' and 'search_index_latency_mean' metrics [JIRA: RIAK-1611]

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho/yokozuna#468]
I suspect the search-related _mean metrics got accidentally left out from this:
https://github.com/basho/riak_kv/pull/855

We have all the others (median, 95, etc), but not mean.
Can we add them?

**Comment by zeeshanlakhani** [comment]
@uwiger wondering if you have any insight into this? Thanks!

**Comment by uwiger** [comment]
I have no objection. In the equivalence tests, metrics that had been added, that were not there in the folsom version, were flagged as errors. Appropriate at the time, I guess, but moving forward, you should of course decide which metrics you want to add.

**Comment by zeeshanlakhani** [comment]
@uwiger cool, that's what i figured... just replicating folsom metrics at the time. thanks.

**Comment by zeeshanlakhani** [comment]
Still in review... but PR in review https://github.com/basho/yokozuna/pull/473.
