### ISSUE TITLE
Upgrade Solr 5.x [JIRA: RIAK-1776]

### ISSUE THREAD

**Issue by mamciek** [basho/yokozuna#489]
Are there any plans on upgrading Solr to version 5.1 / 5.0 ?

**Comment by zeeshanlakhani** [comment]
@mamciek It's on our agenda, but we're in the midst of working through other issues and features with Yokozuna first. It's definitely on radar is the best answer I can give you right now.

**Comment by zeeshanlakhani** [comment]
I'm closing this in favor of https://github.com/basho/yokozuna/issues/185, as we decide on a more stable upgrade path.
