### ISSUE TITLE
Upgrade Solr to 4.10.4 [JIRA: RIAK-1795]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/yokozuna#490]
Moving to 4.10.4 adds a bunch of Solr bugfixes. We should eventually move to Solr 5.x, but that will take a bit more time due to changes in config and such. 

**[Created in JIRA by Zeeshan Lakhani]**

**Comment by zeeshanlakhani** [comment]
solrconfig/solr-xml changes are not meaningful here (5 will need more test). Current tests still need a full rolling upgrade and AAE to repair exchanges (though the built trees already exist and stay through the upgrade).

**Comment by Basho-JIRA** [comment]
Review for 2.2 

**_[posted via JIRA by Seema Jethani]**_

**Comment by mogadanez** [comment]
BTW, SOLR 5.4 is here already, not sure that  Moving to 4.10.4 is valued any more

**Comment by Basho-JIRA** [comment]
Tested this upgrade out with Fred last week, and it all seemed to go smoothly with no modifications. Ran through all the yz riak_test suites, and there were only one or two failures (which I'm still investigating). 

**_[posted via JIRA by Nick Marino]**_

**Comment by Basho-JIRA** [comment]
Turns out all yz tests pass, with the exception of a few which require older installs of Riak that I don't have handy. Hopefully someone else can give those ones a try more easily...if not, let me know and I'll see if I can get them running. 

**_[posted via JIRA by Nick Marino]**_

**Comment by mogadanez** [comment]
Same time Solr 6.0 is out already. =)

**Comment by zeeshanlakhani** [comment]
@mogadanez we'll get this update in but have a plan to move to solr 6 soon afterward (builds off the new configuration needs that is in 5).

**Comment by mogadanez** [comment]
Nice, does it any time frame when 4.10.4 will be ship out?

**Comment by zeeshanlakhani** [comment]
@mogadanez it will be part of 2.2, which is being put together.

**Comment by Basho-JIRA** [comment]
A branch has been created off develop-2.2 which is a cherry-pick from a branch [~zlakhani] created last year:

https://github.com/basho/yokozuna/tree/fd-solr-4.10

All yz_\* riak_tests pass with this version of Solr, though I did find one intermittent failure with yz_facted_search. 

**_[posted via JIRA by Fred Dushin]**_

**Comment by Basho-JIRA** [comment]
Leaving in TODO state, until we better understand the downgrade consequences of updating the lucene match version tag in solrconfig.xml 

**_[posted via JIRA by Fred Dushin]**_
