### ISSUE TITLE
Include JTS jars to be able to use spatial recursive prefix tree types [JIRA: RIAK-1832]

### ISSUE THREAD

**Issue by marksteele** [basho/yokozuna#495]
The jars are missing, which means those types are unavailable. Dropping the jars into the war file will enable those built-in types to start working.

```
 <fieldType name="location_rpt" class="solr.SpatialRecursivePrefixTreeFieldType"
               spatialContextFactory="com.spatial4j.core.context.jts.JtsSpatialContextFactory"
               distErrPct="0.025"
               maxDistErr="0.000009"
               units="degrees"
            />
```

http://sourceforge.net/projects/jts-topo-suite

**Comment by zeeshanlakhani** [comment]
@marksteele I'm not sure we want to include the jts jars by default. Have you tried the suggestions in the threads on the mailing list: http://riak-users.197444.n3.nabble.com/SolrSpatial-Problem-td4033091.html#a4033095? Did that work for you?

**Comment by marksteele** [comment]
Seems kind of silly not to include them, they're a big part of geospatial search.

I installed them manually already, and it appears to work fine. From an end-user of Riak perspective though, it's alot of hoops to get a core piece of Solr working.

Is there a good reason NOT to include them?

**Comment by zeeshanlakhani** [comment]
@marksteele just wanted to make sure things were working for you. This will probably get in eventually. I'll update the ticket when that happens.

**Comment by zeeshanlakhani** [comment]
@marksteele https://github.com/basho/yokozuna/pull/556 will be part of our 2.next cycle.

**Comment by jvoegele** [comment]
Hi @marksteele , unfortunately we are not able to include the JTS JARs at this time due to licensing issues. JTS is released under the LGPL and is incompatible with the Apache license. There has been talk of relicensing JTS under a more liberal license, but to date no action has been taken on this front. For now I'm afraid you'll have to install the JTS JARs manually on each node.

**Comment by zeeshanlakhani** [comment]
Closing until license-issues change.

**Comment by Basho-JIRA** [comment]
Jts jars not license compatible so could not ship them.  There could be apache compatible license jars now but the customer can update themselves.  Per discussion with Fred. 

**_[posted via JIRA by Patricia Brewer]**_
