### ISSUE TITLE
More informative error handling for HTTP requests [JIRA: RIAK-1845]

### ISSUE THREAD

**Issue by JKoff** [basho/yokozuna#498]
In yz_wm_search:search, an error of type other than insufficient_vnodes_available will go to the {RespHeaders, Body} case, causing the request to fail in scrub_headers(error) and obscuring the real error. A possible fix would be to add a clause to yz_wm_search:search to catch other errors such as (warning: untested):

``` erlang
{error, Err} ->
    yz_stat:search_fail(),
    ErrReq = wrq:append_to_response_body(io_lib:format("~p",[Err]), Req),
    ErrReq2 = wrq:set_resp_header("Content-Type", "text/plain", ErrReq),
    {{halt, 503}, ErrReq2, S};
```

This issue is preventing us from getting visibility into why requests are failing in bursts in production. Here's the body of the failed requests:

```
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while proce
ssing this request:<br><pre>{error,
    {error,function_clause,
        [{lists,keydelete3,
             ["Transfer-Encoding",1,error],
             [{file,"lists.erl"},{line,675}]},
         {yz_wm_search,search,2,[{file,"src/yz_wm_search.erl"},{line,138}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,558}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]},
         {webmachine_mochiweb,loop,2,
             [{file,"src/webmachine_mochiweb.erl"},{line,74}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></ht
ml>
```

**Comment by Basho-JIRA** [comment]
I think this is small enough to make the 2.1.2 release. We can always change that though. Depends on review. 

**_[posted via JIRA by Zeeshan Lakhani]**_

**Comment by Basho-JIRA** [comment]
Looks like this landed against 2.0 and can be closed once merged forward to 2.1. 

**_[posted via JIRA by Jon Meredith]**_

**Comment by Basho-JIRA** [comment]
[~jmeredith] yep... https://github.com/basho/yokozuna/pull/534 just needs review 

**_[posted via JIRA by Zeeshan Lakhani]**_

**Comment by Basho-JIRA** [comment]
Thank you kindly, I see the forward merge happened this afternoon, so have tagged FixedVersions with 2.1.2 now it's on the 2.1 branch. 

**_[posted via JIRA by Jon Meredith]**_
