### ISSUE TITLE
On OS X build may not work [JIRA: RIAK-1885]

### ISSUE THREAD

**Issue by jonasrichard** [basho/yokozuna#505]
During grabbing Solr from S3, using wget it fails to get Solr since wget doesn't know the certificate related option.

What if changing the order of using wget and then curl to curl then wget? It works.

https://github.com/basho/yokozuna/blob/a4e2773b946a2a286607462baf875005d49674fc/tools/grab-solr.sh#L38

**Comment by zeeshanlakhani** [comment]
@jonasrichard wget got that option as of 1.10… and I’m on 1.16 now. We’ve had that in the script since yokozuna’s early days (before my time and 2.0). I’m guessing that most would have a more recent version of wget, no?

**Comment by zeeshanlakhani** [comment]
If osx doesn't have `wget` to start with... then that's caught... but if you install it, you'd expect to have a greater version than 1.10.

**Comment by jonasrichard** [comment]
That is ok. I would have needed to run `brew upgrade` more frequently. Probably newly installed systems don't have that issue.
