### ISSUE TITLE
Ring Event + Downed Solr Proc = Bad

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#52]
I'm not sure if this still holds but I have a post-it note saying that if a ring event (yz_events) occurs while the Solr process is down then bad things happen.  Investigate this behavior and fix if there is an issue.

**Comment by coderoshi** [comment]
Verified this is no longer an issue.

All that happens when the solr proc is down is that a call to yz_solr:cores/0 throws an `error_calling_solr` every event tick, until the process comes back up. Everything else works fine, and no ring changes occur.
