### ISSUE TITLE
Yokozuna fails to re-index the remainder of a partition after a non-indexable document is encountered [JIRA: RIAK-2006]

### ISSUE THREAD

**Issue by kesslerm** [basho/yokozuna#525]
When a non-indexable document is encountered during AAE, the yz_exchange_fsm process dies with

```
2015-07-16 09:24:12 =ERROR REPORT====
Error in process <0.6990.0> on node 'dev2@127.0.0.1' with exit value: {{nocatch,{"Failed to index docs",{ok,"400",[{"Content-Type","application/json; charset=UTF-8"},{"Transfer-Encoding","chunked"}],<<106 bytes>>}}},[{yz_solr,index,3,[{file,"src/yz_solr.erl"},{line,199}]},{yz_kv,index,7,[{file,"src/yz_kv.erl"},{line...

2015-07-16 09:24:12.620 [error] emulator Error in process <0.6990.0> on node 'dev2@127.0.0.1' with exit value: {{nocatch,{"Failed to index docs",{ok,"400",[{"Content-Type","application/json; charset=UTF-8"},{"Transfer-Encoding","chunked"}],<<106 bytes>>}}},[{yz_solr,index,3,[{file,"src/yz_solr.erl"},{line,199}]},{yz_kv,index,7,[{file,"src/yz_kv.erl"},{line...
```

At this point the AAE tree build never completes, and consequently no other entries are being re-indexed for the given partition.

Reproduce:
- Set up a bucket with an index.
- Populate the bucket with test-data.
- Verify that Yokozuna returns the correct number of index entries.
- Add one entry that can't be indexed by Solr, e.g. because it has a non-parseable date field. Yokozuna should have logged an error and still return the previous number of entries.
- Stop the cluster, and manually remove the yz/<index_name> directories and the yz_anti_entropy directories from all nodes.
- Restart the cluster and wait for re-indexing to finish. Yokozuna will not be able to reach the full number of index entries again, and return an incoherent set of results. The actual number of missing entries depends on how many entries could be indexed from the affected partition, but will usually be less than the total.

**Comment by zeeshanlakhani** [comment]
@kesslerm never deleting the problematic entry and letting AAE retrigger right?

**Comment by kesslerm** [comment]
@zeeshanlakhani, yes, as long as the problematic entry stays in KV, the issue re-occurs any time AAE runs again.

**Comment by binarytemple** [comment]
Customer [example of issue](https://basho.zendesk.com/agent/tickets/11371), and waiting on patch.

**Comment by zeeshanlakhani** [comment]
@binarytemple this is done, but needs review from @fadushin. It will be going into 2.1.2.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/yokozuna/pull/527

**_[posted via JIRA by Patricia Brewer]**_
