### ISSUE TITLE
Custom extractors prevent AAE re-indexing  [JIRA: RIAK-2173]

### ISSUE THREAD

**Issue by TSiggs** [basho/yokozuna#547]
Current workaround for SOLR re-indexing via wiping yz hash trees breaks when using custom extractors.  
To replicate the issue:
1. Create a custom extractor based on one of our default extractors, and implement it as a custom MIME type.
2. Create a search schema and index, and generate some objects with your custom MIME type. Ensure the bucket used has the schema property set.
3. Create some objects with a new field.
4. Update the schema to include new field, restart Riak.
5. Create a new object with the additional field, and perform a SOLR query against that field. The single object (and not the previous ones create prior to schema change) should show up as a result.
6. Wipe the yz hash trees.
7. After confirming via riak-admin aae-status that all hashes have been rebuilt, perform the query again. No additional results should be found.

**Comment by zeeshanlakhani** [comment]
So, via a r_t, I wasn't able to reproduce this: https://github.com/basho/riak_test/blob/yz-updates/zl/check-for-custom-extractor-issues-and-commit-use/tests/yz_extractors.erl. The main scope of the test for this is here: https://github.com/basho/riak_test/blob/yz-updates/zl/check-for-custom-extractor-issues-and-commit-use/tests/yz_extractors.erl#L30... where we updated the schema, expired, and still got the same result. @TSiggs, I can walk you through this during the week or w/e.

**Comment by zeeshanlakhani** [comment]
@TSiggs any word on this... did you look at my test?

**Comment by TSiggs** [comment]
Hey Zeeshan, I'm doing the sales dog and pony show in Canada right now.  I should have time tomorrow afternoon to give it a try. Thanks for following up!  Get back to you shortly. 

-Tom

**Comment by zeeshanlakhani** [comment]
@TSiggs i may have reproduced, but if they were using allow_mult=true, http, and not following the object update cycle docs, http://docs.basho.com/riak/latest/dev/using/updates/ (pb-oriented libs take care of the context under the hood iirc), then they may get siblings. By using the casual context on the PUT after override, then things shall be fine. Link to the new test: https://github.com/basho/riak_test/blob/844ee9cdb20bd2f476d28fe7ef80967e23d09046/tests/yz_extractors.erl.
