### ISSUE TITLE
Inconsistent search results - Crdts Deletes/Recreates [JIRA: RIAK-2202]

### ISSUE THREAD

**Issue by nrvnrvn** [basho/yokozuna#559]
I have a 4-node cluster, everything is ok.
But search returns me more than 1 document
like

```
In [32]: [svc.client.fulltext_search('documents', '_yz_rk:SOMEKEY')['num_found'] for s in range(10)]
Out[32]: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
```

Riak version = 2.0.2

**Comment by zeeshanlakhani** [comment]
@nicorevin I'm going to close this, as this would be better discussed initially via the mailing list or on the #riak irc.

A few questions to go along w/ this: are you using default bucket_types? are you issuing deletes?

**Comment by nrvnrvn** [comment]
I'm using crdt. After recreating object in a bucket all goes ok. Seems like in some moment in the past the cluster went unbalanced but after rebalancing search still behaves weirdly. Will try reindexing. No big hope for the mailing list btw.

**Comment by zeeshanlakhani** [comment]
@nicorevin so, we've made a fix related to crdts, merges, and search... https://github.com/basho/yokozuna/pull/549 and recreate's a part of that. It'll be an upcoming release. We have a test too: https://github.com/basho/riak_test/pull/862.

**Comment by zeeshanlakhani** [comment]
Also, I'm on the mailing list, so I would have answered there too @nicorevin :).

**Comment by zeeshanlakhani** [comment]
@nicorevin i'll reopen for posterity, but will change the title.

**Comment by zeeshanlakhani** [comment]
Fixed in new work for 2.0.7/2.1.3 release most probably.

**Comment by Basho-JIRA** [comment]
Was fixed for a user.  GH issue is closed.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Vorticity-Flux** [comment]
Any indication when this fix could be generally available? We are also affected by the same problem.
Thank you.

**Comment by zeeshanlakhani** [comment]
As soon as 2.0.7/2.2 are released.
