### ISSUE TITLE
Cleanup/prep YZ startup + shutdown [JIRA: RIAK-2253]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#581]
- Flush the queue on graceful shutdown in yz_app:prep_stop(). 
- Should also call yokozuna:disable(index) (maybe others?) at that point too and maybe unregister API calls.

Related to need(s) in https://github.com/basho/yokozuna/issues/582.

**Comment by zeeshanlakhani** [comment]
Also, todo: https://github.com/basho/yokozuna/pull/565/files#diff-f42188ad89ac358833c9b82d8622c226R44.

Look at prep_stop on kv: https://github.com/basho/riak_kv/blob/2.0/src/riak_kv_app.erl#L226 + http://learnyousomeerlang.com/the-count-of-applications.

**Comment by jvoegele** [comment]
Write a riak_test to verify startup/shutdown behavior.

**Comment by jvoegele** [comment]
@zeeshanlakhani Can you say more concretely what you mean by "flush the queue"? Is there a specific function to call or a message to send to some process?

**Comment by zeeshanlakhani** [comment]
@jvoegele fyi, if I wasn't explicit before, flush the queue, means flush to Solr (which is flushing by readying a worker/batch), but you probably know that via the singular index flush call in https://github.com/basho/yokozuna/pull/565/files#diff-e664002ad0421c9debe8a6ec2b5732b0R198. But, just being double sure.
