### ISSUE TITLE
Implement Flushing of queues [JIRA: RIAK-2254]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#582]
Could implement flush by adding a call to yz_solrq that immediately flushes all indexes to the helper process, and a flush call to the yz_solrq_helper processes that sends back a message when it's read from the mailbox. Wrap yz_solrq_sup with a call to flush on all solrq, then issue flush on all the helpers in parallel and wait for all the responses.

**Comment by zeeshanlakhani** [comment]
^^ @jvoegele

**Comment by zeeshanlakhani** [comment]
Closing, but we should be aware of the perf issue described in https://bashoeng.atlassian.net/browse/RIAK-2628

**Comment by Basho-JIRA** [comment]
Fixed in 2.0.7, forward merged to develop-2.2 

**_[posted via JIRA by Fred Dushin]**_
