### ISSUE TITLE
Prototype/Benchmark/Fix using cursormarks/deep-paging for entropy-data tree building [JIRA: RIAK-2255]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#583]
@fadushin's started looking at this.

**Pay attention** to https://github.com/basho/yokozuna/issues/355. 

Look -> https://github.com/basho/yokozuna/tree/feature/fd/yz-cursors-ed

**Comment by stevegaron** [comment]
Any idea when this will be available? We had to set AAE to passive because our dataset is too big for the tree builder to go through the full dataset without deep paging. It always times out.

**Comment by zeeshanlakhani** [comment]
@stevegaron next release(2.0.7/2.2) will allow configurable timeout for AAE. I will say that after 2.0.7/2.2 are released that this is one of our focused pieces of work and @fadushin already prototyped it. The initial version of this will most likely need a full-reindex though.

**Comment by fadushin** [comment]
@stevegaron Branch is pretty out of date, but you can see the diffs here: https://github.com/basho/yokozuna/compare/2.0...feature/fd/yz-cursors-ed  Requires some care and feeding.

**Comment by stevegaron** [comment]
@zeeshanlakhani @fadushin That's cool. I'm not scared of re-indexing if that gives me more consistent data. Even with configurable timeout, that will never work for me. One of my index bucket is now close to 1 billion docs over 6 nodes... You can't walk that using normal paging ;)

**Comment by zeeshanlakhani** [comment]
@stevegaron we were enumerating through all the terms previously, e.g. https://github.com/basho/yokozuna/blob/develop/java_src/com/basho/yokozuna/handler/EntropyData.java, but cursormarks def. show improvement!

**Comment by Basho-JIRA** [comment]
Prototyping has completed and performance micro-benchmarks have been provided via email. 

**_[posted via JIRA by Fred Dushin]**_
