### ISSUE TITLE
How to handle (or best-listen for) fuse melt/blown events? [JIRA: RIAK-2259]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#587]
Possibly retry batches for search_index, or clear solrq worker(s)? Investigate.

**Comment by zeeshanlakhani** [comment]
@fadushin the retry work should cover this or shall we leave it open?

**Comment by fadushin** [comment]
I think so, though I don't understand the full genesis of this ticket.  In the current batching branch, we listen for fuse blown/recovered events, and we pause batching for indexes that are blown.  Once they recover, batching resumes.  The net effect is that any messages are retried once the fuse recovers, and there is an EQC test to this effect.

**Comment by zeeshanlakhani** [comment]
@fadushin yep... the genesis was to see how we handle things. The #565 branch just moves on... so i think we're covered!

**Comment by JeetKunDoug** [comment]
@fadushin @zeeshanlakhani please close if this is done

**Comment by fadushin** [comment]
This work is covered in the batching batches and retry logic that was added to the worker/helper protocol.

**Comment by Basho-JIRA** [comment]
Fixed in 2.0.7.  We now purge messages when an index fuse is blown, and we hit the HWM.  Otherwise, the message is retried. 

**_[posted via JIRA by Fred Dushin]**_
