### ISSUE TITLE
start fuse to riak boot, and remove need for starting in yz [JIRA: RIAK-2265]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#591]

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_ee/pull/374 + https://github.com/basho/riak/pull/812 

**_[posted via JIRA by Zeeshan Lakhani]**_

**Comment by Basho-JIRA** [comment]
Do not merge until rest of YZ batching is ready to merge. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
Removed the fix version and updated label to reflect the intended versions. The fix version(s) is to be added once this is reviewed and merged/merged forward (if applicable). 

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
Fixed in riak 2.0.7 and forward merged to develop-2.2 

**_[posted via JIRA by Fred Dushin]**_
