### ISSUE TITLE
Update/check/cleanup yz_solrq_eqc.erl + yz_pulseh.erl, and have make test (eunit) run eqc test [JIRA: RIAK-2318]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#602]
a TODO that's related: https://github.com/basho/yokozuna/pull/565/files#diff-faa3c500b7c10f1a9f573e58c6a5d779R11.

Look at riak_core eqc+pulse tests as examples to follow.

**Comment by Basho-JIRA** [comment]
Pulse test has been revived and greatly expanded in 2.0.7 and forward merged to develop-2.2 

**_[posted via JIRA by Fred Dushin]**_
