### ISSUE TITLE
Add yz_fuse r_t test and add/update tests w/ diff batch constraints [JIRA: RIAK-2322]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#603]
^^ @fadushin @jvoegele

**Comment by Basho-JIRA** [comment]
Part of Jason's testing suite... if I remember.  

**_[posted via JIRA by Zeeshan Lakhani]**_

**Comment by Basho-JIRA** [comment]
Fuse tests have been added to the 2.0.7 release and forward merged to develop-2.2 

**_[posted via JIRA by Fred Dushin]**_
