### ISSUE TITLE
Add yz test(s) to test batching configurations [JIRA: RIAK-2323]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#604]
^^ @fadushin @jvoegele 

To be clear, we don't currently have a comprehensive set of riak_tests for batching, but we want at least one test that exercises the main batching components and their configuration settings.  We'll probably want to do this with and without AAE, so as to minimize non-determinism when AAE is active.

**Comment by Basho-JIRA** [comment]
yz_solrq_test was added in 2.0.7 and forward merged to develop-2.2 

**_[posted via JIRA by Fred Dushin]**_
