### ISSUE TITLE
test (maybe fix?) issue around node joining coverage plan even though Solr and or partial solr cores not up yet [JIRA: RIAK-2444]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/yokozuna#623]
- We have an [is_up](https://github.com/basho/yokozuna/blob/hotfix/2.0.6-2012.08.25/src/yz_solr_proc.erl#L120) check for the solr proc start, for which a node can then become part of the coverage plan... but maybe this doesn't cover 
- Though we cache plans, the event tick should recalc it, but something to look at if this throws an error on query while a node restarts 
- we've heard from @kesslerm that solr can take a min or two to start-up, esp w/ many cores... but according the the check above, a node will only join the plan once solr is generally (heartbeating) available

**Comment by Basho-JIRA** [comment]
https://github.com/basho/yokozuna/pull/645 

**_[posted via JIRA by Jason Voegele]**_
