### ISSUE TITLE
searching using pagination gives OOM on the riak side [JIRA: RIAK-2497]

### ISSUE THREAD

**Issue by vedil** [basho/yokozuna#628]
I have say user objects around 12K and i am doing a paginated search and trying to get the last page by using query like q=_:_&start=12020&rows=20&wt=json.

when i try this query using http, i get results back
tried with python client , i get results back
with java client, solr goes into OOM

attaching the log fragments in the file.
[log.txt](https://github.com/basho/yokozuna/files/216781/log.txt)

**Comment by vedil** [comment]
some more info on it is the http query is also failing when i have sort in the query.
i missed to add sort for htttp query (which was there in the java query) and saw that it is successful.
but with adding sort even http query fails with below stack trace

{"error":{"msg":"java.lang.OutOfMemoryError: Java heap space","trace":"java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space\n\tat org.apache.solr.servlet.SolrDispatchFilter.sendError(SolrDispatchFilter.java:796)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:448)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:217)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:368)\n\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)\n\tat org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)\n\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)\n\tat org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.OutOfMemoryError: Java heap space\n","code":500}}

**Comment by kesslerm** [comment]
As an alternative to using the `start` parameter, you can iterate over Solr result sets using `cursorMark`. See https://cwiki.apache.org/confluence/display/solr/Pagination+of+Results and http://solr.pl/en/2014/03/10/solr-4-7-efficient-deep-paging/ for more details.

`cursorMark` is not currently available through the protocol buffer interface used by the majority of the Riak client implementations. However, Riak's HTTP Search API can be used instead. If necessary, write custom client code to use this API for search requests.

**Comment by vedil** [comment]
thanks for the info, will  try this (can not do right away :( ) . will update the results once i make the required changes.

**Comment by zeeshanlakhani** [comment]
closing as we have an open issue for cursormark impl.
