### ISSUE TITLE
Compress 'fq' (Filter Query)

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#72]
Yokozuna uses Solr filter queries in order to eliminate overlapping data which would cause incorrect results to be returned.  While running benchmarks on an 8-node baremetal cloud cluster (see issue #44) I found that the filter query can be built in a smarter manner and reduce the amount of work done per query.

Currently YZ builds a `fq` like this ('p' stands for partition):

```
(<nodeA> AND <p1>) OR (<nodeB> AND <p4>) OR (<nodeC> AND <p7>) OR (<nodeA> AND <p10>) OR ...
```

Notice how `<nodeA>` is repeated.  Each unique node/partition combo gets its own group query.  This can be compressed down like so:

```
(<nodeA> AND (<p1> OR <p10> OR ..)) OR (<nodeA> AND (<p4> OR <p13> OR ...)) OR ...
```

This reduces the amount of work Solr needs to do for each query.  It can be reduced even further as the node filtering is only needed if an ownership change is in play.

```
<p1> OR <p4> OR <p7> OR ...
```

The first level of compression is an easy change to make.  The second one will take a little more work as it requires keeping tabs on ownership changes, but it should be doable.

Finally, if the moons and stars align, you can remove the filter query altogether.  This depends on several factors:
- ring size
- number of nodes
- ownership claim (e..g. v2 vs. v3)
- is cluster currently under ownership transfer

Removing the filter query gives a substantial boost in query performance.  It should be easy enough to detect when conditions are right to remove the filter query.  But I might leave that work to wait for another ticket.  I just thought I'd mention it here so that the idea doesn't get lost.

First stage: #76

**Comment by hectcastro** [comment]
You may already be aware of this, and I don't believe it applies in this specific situation, but when you want the intersection of multiple filter queries you can pass multiple `fq` query string parameters (`?fq=...fq=...`). Solr caches each `fq` individually, which yields some performance benefits if one or all of them are common across many queries.

**Comment by coderoshi** [comment]
@hectcastro sadly, concatenating multiple `fq`s is only conjunctive, where in this case, disjunction is required

**Comment by rzezeski** [comment]
@hectcastro I'm not sure I follow how

`?fq=Q1 AND Q2`

is different from

`?fq=Q1&fq=Q2`

It is my understand that in both cases Q1 and Q2 will have their bit-sets cached.  Also, as @coderoshi said I need disjunction, this would only work if the default op param also applies to filter queries.

**Comment by hectcastro** [comment]
To clarify, it doesn't apply in this case (like @coderoshi mentioned). But my understanding of how Solr's filter cache works is that there is a difference between:

```
?fq=Q1 AND Q2
```

and

```
?fq=Q1&fq=Q2
```

In the latter, each `fq` is a separate entry in the filter cache, so that later if you end up with:

```
?fq=Q1&fq=Q3
```

The cached `fq=Q1` will be used. If you had all of the conditions in one `fq`, like the first example, I'm sure some other Solr caches would get touched, but the filter query cache would not unless you had an identical `fq`. In the past, when I broke out query strings into multiple `fq` (when possible), I saw in increase in filter query cache hit ratios.

**Comment by rzezeski** [comment]
@hectcastro very good to know.  Now I'm curious if default op applies to fq as well.  Might play around with this.

**Comment by rzezeski** [comment]
So the first stage of this issue definitely helped and is already merged.

I had a branch for the 2nd stage but have somehow misplaced it :(  I'm not sure how much it helped, though.  I didn't get a chance to do proper benchmarking.

The 3rd stage is probably just an illusion I believe especially as claim tries diversify ownership as much as possible.

I'm moving this to 0.7.0 for now to revisit the 2nd stage.

**Comment by rzezeski** [comment]
I've decided to punt on the 2nd and 3rd stages.

The 2nd stage would be based on checking the ring to determine if there are ownership changes but it also relies on Yokozuna dropping indexes after a partition has moved.  This drop operation is based on a tick and might lag behind the moment the ring declares ownership has finished.  Rather than complicate the logic, making the system more brittle, I'm going to punt.  Besides, two future changes will help in this area 1) adding ability to minimize number of nodes in coverage plans and 2) adding a "partition factor" per index which allows an index to live on a subset of the nodes in a cluster.
