### ISSUE TITLE
/bin/bashism found in priv/ shell scripts

### ISSUE THREAD

**Issue by jj1bdx** [basho/yokozuna#74]
While building on FreeBSD 9.1-STABLE, the following scripts were unable to execute: `priv/build-jar.sh` and `priv/grab-solr.sh`.

I was hitting this issue when I was working on Riak - maybe @jaredmorrow knows this issue better than me.

The quick hack for FreeBSD is changing `#!/bin/bash` to `#!/usr/local/bin/bash`, but I don't recommend this because it includes an absolute path. Maybe `#!/usr/bin/env bash`? (Correct me if I'm wrong)

**Comment by jaredmorrow** [comment]
@jj1bdx can you give the latest master a try, should work just fine now on FreeBSD.

**Comment by jj1bdx** [comment]
https://github.com/basho/yokozuna/issues/77 worked. Thanks. This issue is closed.

Another dep issue found. See https://github.com/basho/riak/pull/293
