### ISSUE TITLE
JSON extractor

### ISSUE THREAD

**Issue by teburd** [basho/yokozuna#9]
Would be good to basically support all the content types that are currently supported by riak_search

**Comment by rzezeski** [comment]
Definitely agree that JSON should be supported.  I added it to the 0.1 milestone with is the end of this month.  I'm not sure I agree with adding in the erlang extractors yet.  I want to take it one at a time.

**Comment by rzezeski** [comment]
A JSON extractor has been added. See be0c445f7a4ef068f25afa942df374805ee71c68
